# Generated by Django 5.1.5 on 2026-08-15 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('processed', 'Обработано'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='events_outb_status_1831f4_idx')],
            },
        ),
    ]
