# Generated by Django 5.1.5 on 2026-08-04 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('employees', '0002_alter_employee_options'),
        ('organizations', '0001_initial'),
        ('tasks', '0003_task_recurrence_rule_task_scheduled_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge_base.knowledgecategory')),
            ],
            options={
                'verbose_name_plural': 'Категории базы знаний',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('BOOK', 'Книга'), ('PDF', 'PDF'), ('PRESENTATION', 'Презентация'), ('DOCUMENT', 'Документ'), ('VIDEO', 'Видео'), ('INSTRUCTION', 'Инструкция'), ('REGULATION', 'Регламент'), ('POLICY', 'Политика'), ('TTK', 'ТТК'), ('HACCP', 'ХАССП'), ('TECHNICAL_DOCUMENTATION', 'Техническая документация'), ('TEMPLATE', 'Шаблон'), ('IMAGE', 'Изображение'), ('EXTERNAL_LINK', 'Внешняя ссылка')], max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('REVIEW', 'На проверке'), ('PUBLISHED', 'Опубликован'), ('NEEDS_UPDATE', 'Требует обновления'), ('ARCHIVED', 'Архив')], default='DRAFT', max_length=20)),
                ('language', models.CharField(default='ru', max_length=12)),
                ('cover_image', models.FileField(blank=True, upload_to='knowledge/covers/%Y/%m/')),
                ('is_required', models.BooleanField(default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('review_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='knowledge_base.knowledgecategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_knowledge_materials', to=settings.AUTH_USER_MODEL)),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_materials', to='organizations.department')),
                ('tags', models.ManyToManyField(blank=True, related_name='materials', to='knowledge_base.materialtag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=150)),
                ('access_level', models.CharField(choices=[('VIEW', 'Просмотр'), ('DOWNLOAD', 'Скачивание'), ('EDIT', 'Редактирование'), ('MANAGE', 'Управление')], default='VIEW', max_length=12)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_access_rules', to='organizations.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_access_rules', to='employees.employee')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_access_rules', to='organizations.facility')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='knowledge_base.knowledgematerial')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_access_rules', to='organizations.region')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_access_rules', to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='knowledge/materials/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('external_url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('requires_reacknowledgment', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_versions', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge_base.knowledgematerial')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAcknowledgmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Назначено'), ('OPENED', 'Открыто'), ('ACKNOWLEDGED', 'Ознакомлен'), ('OVERDUE', 'Просрочено'), ('CANCELLED', 'Отменено')], default='ASSIGNED', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_material_acknowledgments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_acknowledgments', to='employees.employee')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_acknowledgments', to='tasks.task')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgment_assignments', to='knowledge_base.materialversion')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgematerial',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_materials', to='knowledge_base.materialversion'),
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_views', to='employees.employee')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='knowledge_base.knowledgematerial')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='knowledge_base.materialversion')),
            ],
        ),
        migrations.CreateModel(
            name='TTKMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(blank=True, max_length=240)),
                ('output_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('technology', models.TextField(blank=True)),
                ('storage_requirements', models.TextField(blank=True)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ttk_metadata', to='knowledge_base.knowledgematerial')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_favorites', to='employees.employee')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='knowledge_base.knowledgematerial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('material', 'employee'), name='unique_material_employee_favorite')],
            },
        ),
        migrations.AddConstraint(
            model_name='materialversion',
            constraint=models.UniqueConstraint(fields=('material', 'version'), name='unique_material_version'),
        ),
        migrations.AddConstraint(
            model_name='materialacknowledgmentassignment',
            constraint=models.UniqueConstraint(fields=('version', 'employee'), name='unique_version_employee_acknowledgment'),
        ),
        migrations.AddConstraint(
            model_name='materialview',
            constraint=models.UniqueConstraint(fields=('material', 'employee'), name='unique_material_employee_view'),
        ),
    ]
