# Generated by Django 5.1.5 on 2026-08-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task', 'Задача'), ('checklist', 'Чек-лист'), ('incident', 'Инцидент'), ('sensor', 'Датчик'), ('system', 'Система'), ('course_assigned', 'Курс назначен'), ('course_due_soon', 'Срок курса приближается'), ('course_overdue', 'Курс просрочен'), ('course_completed', 'Курс завершён'), ('assessment_failed', 'Тест не пройден'), ('certificate_issued', 'Сертификат выдан'), ('certificate_expiring', 'Сертификат истекает'), ('certificate_expired', 'Сертификат истёк'), ('material_ack_required', 'Требуется ознакомление'), ('material_ack_overdue', 'Ознакомление просрочено')], max_length=40),
        ),
    ]
