# Generated by Django 5.1.5 on 2026-08-30 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('notifications', '0004_seed_notification_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramWebhookEvent',
            fields=[
                ('update_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('command', models.CharField(blank=True, max_length=32)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=32)),
                ('result_code', models.CharField(blank=True, max_length=80)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='last_error_code',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='provider_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='routing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationdeliveryattempt',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notificationdeliveryattempt',
            name='outcome',
            field=models.CharField(default='failed', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationdeliveryattempt',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('telegram', 'Telegram'), ('email', 'Email')], default='in_app', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('retry', 'Retry'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('unknown', 'Unknown')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('telegram', 'Telegram'), ('email', 'Email')], default='in_app', max_length=20),
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=240)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_templates', to='notifications.notificationtemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'channel'), name='notification_unique_channel_template')],
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_chat_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=80)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('linked_at', models.DateTimeField()),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_disabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_accounts', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee',), name='telegram_one_active_per_employee'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telegram_user_id',), name='telegram_one_active_per_user')],
            },
        ),
    ]
