# Generated by Django 5.1.5 on 2026-08-03 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('responsible_role', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=20)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('escalation_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_haccp', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='organizations.facility')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_snapshot', models.JSONField(default=dict)),
                ('due_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Назначен'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('violation', 'Есть нарушения'), ('cancelled', 'Отменён')], default='assigned', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_reinspection', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_runs', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.facility')),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklistrun')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.zone')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='checklists.checklisttemplate')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('question_type', models.CharField(choices=[('boolean', 'Да / Нет'), ('text', 'Текст'), ('number', 'Число'), ('temperature', 'Температура'), ('humidity', 'Влажность'), ('rating', 'Оценка'), ('photo', 'Фотография'), ('file', 'Файл'), ('single', 'Один вариант'), ('multiple', 'Несколько вариантов'), ('signature', 'Подпись'), ('acknowledgement', 'Подтверждение')], max_length=24)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('failure_creates_task', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='checklists.checklisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='high', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklists.checklistquestion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='checklists.checklistrun')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_violations', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('comment', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklists.checklistquestion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklists.checklistrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'question'), name='unique_run_question_answer')],
            },
        ),
    ]
