# Generated by Django 5.1.5 on 2026-08-04 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrun',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='default_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_checklist_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='checklistrun',
            constraint=models.UniqueConstraint(condition=models.Q(('scheduled_for__isnull', False)), fields=('template', 'scheduled_for'), name='unique_checklist_schedule_period'),
        ),
    ]
