from django.conf import settings
from django.db import models
class Sensor(models.Model):
    class Type(models.TextChoices): TEMPERATURE="temperature","Температура"; HUMIDITY="humidity","Влажность"; DOOR="door","Открытие двери"; CO2="co2","CO₂"; PRESSURE="pressure","Давление"; POWER="power","Питание"; SIGNAL="signal","Сигнал"; BATTERY="battery","Батарея"; UNIVERSAL="universal","Универсальный"
    class State(models.TextChoices): NORMAL="normal","Норма"; WARNING="warning","Предупреждение"; CRITICAL="critical","Критическое отклонение"; OFFLINE="offline","Нет связи"; MAINTENANCE="maintenance","Обслуживание"
    name=models.CharField(max_length=180);serial_number=models.CharField(max_length=80,unique=True);sensor_type=models.CharField(max_length=24,choices=Type.choices);manufacturer=models.CharField(max_length=100,blank=True);model=models.CharField(max_length=100,blank=True)
    facility=models.ForeignKey("organizations.Facility",on_delete=models.CASCADE,related_name="sensors");zone=models.ForeignKey("organizations.Zone",on_delete=models.SET_NULL,null=True,blank=True,related_name="sensors");equipment=models.CharField(max_length=180,blank=True);unit=models.CharField(max_length=20)
    allowed_min=models.DecimalField(max_digits=10,decimal_places=2);allowed_max=models.DecimalField(max_digits=10,decimal_places=2);critical_min=models.DecimalField(max_digits=10,decimal_places=2);critical_max=models.DecimalField(max_digits=10,decimal_places=2);allowed_deviation_minutes=models.PositiveIntegerField(default=15);transmission_interval_seconds=models.PositiveIntegerField(default=300)
    installed_at=models.DateField();serviced_at=models.DateField(null=True,blank=True);battery_level=models.PositiveSmallIntegerField(default=100);signal_quality=models.PositiveSmallIntegerField(default=100);state=models.CharField(max_length=20,choices=State.choices,default=State.NORMAL);responsible=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True);last_reading_at=models.DateTimeField(null=True,blank=True);is_demo=models.BooleanField(default=False)
    class Meta: ordering=["facility","name"]
class SensorReading(models.Model):
    sensor=models.ForeignKey(Sensor,on_delete=models.CASCADE,related_name="readings");value=models.DecimalField(max_digits=12,decimal_places=3);level=models.CharField(max_length=20,choices=Sensor.State.choices);recorded_at=models.DateTimeField(db_index=True);received_at=models.DateTimeField(auto_now_add=True)
    class Meta: ordering=["-recorded_at"];indexes=[models.Index(fields=["sensor","recorded_at"])]
class SensorHourlyAggregate(models.Model):
    sensor=models.ForeignKey(Sensor,on_delete=models.CASCADE,related_name="hourly_aggregates");hour=models.DateTimeField();minimum=models.DecimalField(max_digits=12,decimal_places=3);maximum=models.DecimalField(max_digits=12,decimal_places=3);average=models.DecimalField(max_digits=12,decimal_places=3);measurement_count=models.PositiveIntegerField();outside_norm_seconds=models.PositiveIntegerField(default=0);offline_seconds=models.PositiveIntegerField(default=0);warning_count=models.PositiveIntegerField(default=0);critical_count=models.PositiveIntegerField(default=0)
    class Meta: constraints=[models.UniqueConstraint(fields=["sensor","hour"],name="unique_sensor_hour")];ordering=["hour"]
class SensorEvent(models.Model):
    sensor=models.ForeignKey(Sensor,on_delete=models.CASCADE,related_name="events");level=models.CharField(max_length=20,choices=Sensor.State.choices);started_at=models.DateTimeField();ended_at=models.DateTimeField(null=True,blank=True);peak_value=models.DecimalField(max_digits=12,decimal_places=3,null=True);task=models.ForeignKey("tasks.Task",on_delete=models.SET_NULL,null=True,blank=True);created_at=models.DateTimeField(auto_now_add=True)
