# Generated by Django 5.2.17 on 2026-09-15 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_stage_project_guard'),
        ('work_tasks', '0004_lock_acceptance_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttasklink',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='projecttasklink',
            name='unlinked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectTaskLinkHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('link', 'Привязка'), ('unlink', 'Отвязка'), ('stage', 'Перенос этапа'), ('project', 'Перенос проекта')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_task_link_changes', to=settings.AUTH_USER_MODEL)),
                ('new_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_task_links', to='projects.project')),
                ('new_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_task_links', to='projects.projectstage')),
                ('old_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_task_links', to='projects.project')),
                ('old_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_task_links', to='projects.projectstage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_link_history', to='work_tasks.task')),
            ],
        ),
    ]
