# Generated by Django 5.2.17 on 2026-09-15 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_account_access_state'),
        ('projects', '0003_projecttasklink_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectMilestoneHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('confirm', 'Подтверждение'), ('reopen', 'Повторное открытие')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_milestone_changes', to='employees.employee')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='projects.projectmilestone')),
            ],
        ),
    ]
