# Generated by Django 5.2.17 on 2026-09-15 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_account_access_state'),
        ('projects', '0005_projectattachment_projectcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestoneDueNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_notices', to='projects.projectmilestone')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('milestone', 'due_at', 'recipient'), name='project_due_notice_once')],
            },
        ),
    ]
