# Generated by Django 5.1.5 on 2026-08-15 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_assignmenttarget_functionalgroup_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('location_type', models.CharField(blank=True, max_length=64)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organizations.legalentity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.location')),
            ],
            options={
                'indexes': [models.Index(fields=['parent'], name='organizatio_parent__c7e758_idx'), models.Index(fields=['legal_entity'], name='organizatio_legal_e_a527b9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='location_parent_not_self')],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('unit_type', models.CharField(blank=True, max_length=64)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_units', to='organizations.legalentity')),
                ('manager_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_org_units', to='employees.employee')),
                ('manager_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_org_units', to='employees.position')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.orgunit')),
            ],
            options={
                'indexes': [models.Index(fields=['parent'], name='organizatio_parent__71415a_idx'), models.Index(fields=['legal_entity'], name='organizatio_legal_e_b5615b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='org_unit_parent_not_self')],
            },
        ),
    ]
