# Generated by Django 5.2.17 on 2026-09-01 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_team_teammembership_teamnumbersequence_and_more'),
        ('organizations', '0002_legalentity_location_orgunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='short_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.CharField(choices=[('company', 'Компания'), ('direction', 'Направление'), ('division', 'Дивизион'), ('department', 'Отдел'), ('branch', 'Филиал'), ('facility', 'Объект'), ('section', 'Секция'), ('other', 'Другое')], default='other', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='org_unit_valid_period'),
        ),
    ]
