# Generated by Django 5.2.17 on 2026-10-02 10:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_account_access_state'),
        ('organizations', '0003_orgunit_description_orgunit_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='location',
            name='business_status',
            field=models.CharField(blank=True, choices=[('preparation', 'Подготовка'), ('operating', 'Работает'), ('seasonal_closed', 'Сезонно закрыт'), ('final_closed', 'Окончательно закрыт')], max_length=24),
        ),
        migrations.AddField(
            model_name='location',
            name='business_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Ресторан'), ('bar', 'Бар'), ('nightclub', 'Ночной клуб'), ('hotel', 'Отель'), ('dormitory', 'Общежитие'), ('warehouse', 'Склад'), ('production', 'Производство'), ('office', 'Офис'), ('technical', 'Технический объект'), ('other', 'Другое')], max_length=24),
        ),
        migrations.AddField(
            model_name='location',
            name='contacts',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='location',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='node_kind',
            field=models.CharField(choices=[('unclassified', 'Не классифицировано'), ('geography', 'География'), ('site', 'Площадка'), ('object', 'Объект'), ('zone', 'Зона')], db_index=True, default='unclassified', max_length=24),
        ),
        migrations.AddField(
            model_name='location',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='location',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='location',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='LocationIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'operation', 'key'), name='location_idempotency_actor_operation_key')],
            },
        ),
        migrations.CreateModel(
            name='LocationResponsibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Управляющий'), ('technical', 'Технический ответственный')], max_length=24)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_responsibilities', to='employees.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='organizations.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('location', 'role'), name='location_one_current_responsible'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='location_responsibility_period')],
            },
        ),
    ]
