# Generated by Django 5.1.5 on 2026-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=80)),
                ('instance_id', models.CharField(max_length=120)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('items_processed', models.PositiveBigIntegerField(default=0)),
                ('metadata_safe', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['worker_name', 'last_seen_at'], name='ops_worker_seen')],
                'constraints': [models.UniqueConstraint(fields=('worker_name', 'instance_id'), name='operations_worker_instance')],
            },
        ),
    ]
