# Generated by Django 5.1.5 on 2026-08-03 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('sensors', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_type', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('peak_value', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('normalized_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('notified', 'Уведомление отправлено'), ('acknowledged', 'Подтверждён'), ('in_progress', 'В работе'), ('escalated', 'Эскалирован'), ('normalized', 'Показатель нормализован'), ('closed', 'Закрыт'), ('false_alarm', 'Ложное срабатывание')], default='open', max_length=20)),
                ('is_demo', models.BooleanField(default=False)),
                ('response_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklistrun')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='sensors.sensor')),
                ('sensor_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident', to='sensors.sensorevent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='tasks.task')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
