import { test, expect, Page } from '@playwright/test';
import { readFileSync } from 'node:fs';

const fixture=JSON.parse(readFileSync('/private/projects-fixture.json','utf8'));
async function login(page:Page,actor:any){await page.goto('/');await page.getByLabel('Электронная почта').fill(actor.email);await page.getByLabel('Пароль',{exact:true}).fill(actor.password);await page.getByRole('button',{name:'Войти',exact:true}).click();await expect(page.getByLabel('Меню аккаунта')).toBeVisible();}

test('account menu separates profile view, edit and logout state',async({page})=>{
  await login(page,fixture.actors.manager);
  await page.goto('/projects');
  await page.screenshot({path:'/artifacts/sidebar-expanded.png',fullPage:true});
  await page.getByRole('button',{name:'Работа'}).click();
  await expect(page.getByRole('button',{name:'Работа'})).toHaveAttribute('aria-expanded','false');
  await page.screenshot({path:'/artifacts/sidebar-collapsed.png',fullPage:true});
  const account=page.getByLabel('Меню аккаунта');
  await account.focus();await page.keyboard.press('Enter');
  await expect(page.getByRole('menuitem',{name:'Мой профиль'})).toBeVisible();
  await page.keyboard.press('Escape');await expect(account).toBeFocused();
  await page.keyboard.press('Space');
  await page.getByRole('menuitem',{name:'Мой профиль'}).click();
  await expect(page).toHaveURL(/\/people\/me$/);
  await expect(page.getByRole('heading',{name:'Мой профиль',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:/Сохранить|Редактировать/})).toHaveCount(0);
  await expect(page.getByLabel('Загрузить аватар')).toHaveCount(0);
  await account.click();await page.getByRole('menuitem',{name:'Редактировать профиль'}).click();
  await expect(page).toHaveURL(/\/people\/me\/edit$/);
  await expect(page.getByRole('heading',{name:'Редактировать профиль'})).toBeVisible();
  await expect(page.getByLabel('Загрузить аватар')).toBeVisible();
  await expect(page.getByText('Видимость данных')).toBeVisible();
  await expect(page.getByText('Кадровые данные изменяются после согласования')).toBeVisible();
  await page.getByLabel('Загрузить аватар').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')});
  await expect(page.getByRole('button',{name:'Удалить аватар'})).toBeVisible();
  await page.getByRole('button',{name:'Удалить аватар'}).click();
  await expect(page.getByRole('button',{name:'Удалить аватар'})).toHaveCount(0);
  const bioVisibility=page.getByRole('combobox',{name:'О себе'});
  await bioVisibility.selectOption('managers');await expect(bioVisibility).toHaveValue('managers');
  await page.getByLabel('Новое значение').fill('+7 000 000-00-00');
  await page.getByLabel('Причина').fill('Синтетическая browser-проверка согласования');
  await page.getByRole('button',{name:'Отправить на согласование'}).click();
  await expect(page.locator('.change-request-list')).toContainText('work_phone');
  const bio=page.getByRole('textbox',{name:'О себе'});await bio.fill('Несохранённое синтетическое описание');
  await page.route('**/api/internal/v1/people/me/',route=>route.request().method()==='PATCH'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'Синтетическая ошибка API'})}):route.continue(),{times:1});
  await page.getByRole('button',{name:'Сохранить',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Синтетическая ошибка API');
  await expect(bio).toHaveValue('Несохранённое синтетическое описание');
  page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Отмена'}).click();
  await expect(page).toHaveURL(/\/people\/me$/);
  await page.setViewportSize({width:390,height:844});
  await account.click();await expect(page.getByRole('menu')).toBeVisible();
  await page.getByRole('menuitem',{name:'Редактировать профиль'}).click();
  await expect(page.getByRole('heading',{name:'Редактировать профиль'})).toBeVisible();
  await page.getByLabel('Открыть основное меню').click();await expect(page.getByRole('navigation',{name:'Основная навигация'})).toBeVisible();
  await page.keyboard.press('Escape');await expect(page.getByLabel('Открыть основное меню')).toBeFocused();
  await page.goto('/people/me');
  await page.setViewportSize({width:1440,height:900});
  await account.click();await page.getByRole('menuitem',{name:'Выйти'}).click();
  await expect(page.getByRole('button',{name:'Войти',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>sessionStorage.length)).toBe(0);
  await login(page,fixture.actors.outsider);
  await account.click();
  await expect(page.getByRole('menu').getByText(fixture.actors.outsider.email)).toBeVisible();
  const keys=await page.evaluate(()=>Object.keys(localStorage).filter(key=>key.startsWith('ays-sidebar-groups:')));
  expect(keys.length).toBeGreaterThanOrEqual(2);
});
