# Generated by Django 5.1.5 on 2026-08-03 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20)),
                ('criticality', models.PositiveSmallIntegerField(default=1)),
                ('complexity', models.PositiveSmallIntegerField(default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('initial_deadline', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('requires_comment', models.BooleanField(default=False)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_file', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Ручная постановка'), ('checklist', 'Чек-лист'), ('haccp', 'ХАССП'), ('sensor', 'Тревога датчика'), ('incident', 'Инцидент'), ('request', 'Техническое обращение'), ('schedule', 'Расписание'), ('document', 'Документ'), ('training', 'Обучение'), ('integration', 'Интеграция')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('assigned', 'Назначена'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('waiting', 'Ожидает информации'), ('approval', 'На согласовании'), ('review', 'На проверке'), ('completed', 'Выполнена'), ('closed', 'Закрыта'), ('returned', 'Возвращена'), ('cancelled', 'Отменена')], default='draft', max_length=20)),
                ('result_text', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvers', models.ManyToManyField(blank=True, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organizations.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organizations.facility')),
                ('observers', models.ManyToManyField(blank=True, related_name='observed_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organizations.zone')),
            ],
            options={
                'ordering': ['deadline', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('after_completion', 'После завершения'), ('event', 'По событию')], max_length=30)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_deadline', models.DateTimeField()),
                ('proposed_deadline', models.DateTimeField()),
                ('reason_type', models.CharField(choices=[('assignee', 'По вине исполнителя'), ('manager', 'По инициативе руководителя'), ('employee', 'Зависимость от сотрудника'), ('department', 'Зависимость от подразделения'), ('contractor', 'Задержка подрядчика'), ('technical', 'Техническая причина'), ('force_majeure', 'Форс-мажор')], max_length=30)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deadline_requests', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_requests', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
