# Generated by Django 5.1.5 on 2026-08-15 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('organizations', '0002_legalentity_location_orgunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_roles', to='organizations.legalentity'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_roles', to='organizations.location'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_roles', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='access_control.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='access_control.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='access_control.role'),
        ),
        migrations.AddIndex(
            model_name='employeerole',
            index=models.Index(fields=['employee'], name='access_cont_employe_5cc3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerole',
            index=models.Index(fields=['role'], name='access_cont_role_id_da9ceb_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeerole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'role', 'org_unit', 'legal_entity', 'location'), name='unique_active_employee_role_context'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission', 'scope'), name='unique_role_permission_scope'),
        ),
    ]
