# Generated by Django 5.2.17 on 2026-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='scope',
            field=models.CharField(choices=[('own', 'Собственные'), ('participating', 'С участием'), ('team', 'Команда'), ('org_unit', 'Подразделение'), ('legal_entity', 'Юридическое лицо'), ('global', 'Глобально'), ('location', 'Объект и его зоны')], max_length=24),
        ),
    ]
