# Generated by Django 5.1.5 on 2026-08-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('checklists', '0002_checklistrun_scheduled_for_and_more'),
        ('employees', '0002_alter_employee_options'),
        ('incidents', '0001_initial'),
        ('knowledge_base', '0001_initial'),
        ('organizations', '0001_initial'),
        ('tasks', '0003_task_recurrence_rule_task_scheduled_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=360)),
                ('cover_image', models.FileField(blank=True, upload_to='learning/covers/%Y/%m/')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('passing_score', models.PositiveSmallIntegerField(default=80)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('certificate_validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('repeat_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('REVIEW', 'На проверке'), ('PUBLISHED', 'Опубликован'), ('ARCHIVED', 'Архив')], default='DRAFT', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_courses', to=settings.AUTH_USER_MODEL)),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='organizations.department')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=150)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_rules', to='learning.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_audience_rules', to='organizations.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_audience_rules', to='employees.employee')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_audience_rules', to='organizations.facility')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_audience_rules', to='organizations.region')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_audience_rules', to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='learning.coursecategory')),
            ],
            options={
                'verbose_name_plural': 'Категории курсов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='learning.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.course')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('lesson_type', models.CharField(choices=[('TEXT', 'Текст'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ'), ('PRESENTATION', 'Презентация'), ('IMAGE', 'Изображение'), ('EXTERNAL_LINK', 'Внешняя ссылка'), ('PRACTICAL_TASK', 'Практическое задание'), ('ASSESSMENT', 'Тестирование')], max_length=24)),
                ('content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='knowledge_base.knowledgematerial')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.coursemodule')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Назначено'), ('NOT_STARTED', 'Не начато'), ('IN_PROGRESS', 'В процессе'), ('WAITING_ASSESSMENT', 'Ожидает тестирования'), ('COMPLETED', 'Завершено'), ('FAILED', 'Не пройдено'), ('OVERDUE', 'Просрочено'), ('CANCELLED', 'Отменено'), ('EXPIRED', 'Истёк срок')], default='ASSIGNED', max_length=24)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Вручную'), ('ROLE_RULE', 'По роли'), ('POSITION_RULE', 'По должности'), ('DEPARTMENT_RULE', 'По подразделению'), ('ONBOARDING', 'Адаптация'), ('INCIDENT', 'Инцидент'), ('HACCP_VIOLATION', 'Нарушение ХАССП'), ('CHECKLIST_VIOLATION', 'Нарушение чек-листа'), ('DOCUMENT_UPDATE', 'Обновление документа'), ('CERTIFICATE_EXPIRATION', 'Истечение допуска'), ('SCHEDULE', 'Расписание')], default='MANUAL', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='learning.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='employees.employee')),
                ('related_checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to='checklists.checklistrun')),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to='incidents.incident')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to='tasks.task')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_assignments', to='learning.lesson')),
            ],
            options={
                'ordering': ['due_at', '-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='learning.courseassignment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='learning.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assignment', 'lesson'), name='unique_assignment_lesson_progress')],
            },
        ),
    ]
