# Generated by Django 5.1.5 on 2026-08-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('passing_score', models.PositiveSmallIntegerField(default=80)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('questions_per_attempt', models.PositiveIntegerField(blank=True, null=True)),
                ('show_correct_answers', models.BooleanField(default=False)),
                ('allow_review', models.BooleanField(default=True)),
                ('manual_review_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Действует'), ('EXPIRING', 'Истекает'), ('EXPIRED', 'Истёк'), ('REVOKED', 'Отозван')], default='ACTIVE', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='learning/certificates/%Y/%m/')),
                ('verification_code', models.CharField(max_length=64, unique=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='learning.courseassignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='learning.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employees.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Один вариант'), ('MULTIPLE_CHOICE', 'Несколько вариантов'), ('TRUE_FALSE', 'Да/нет'), ('TEXT', 'Текст'), ('NUMBER', 'Число'), ('MATCHING', 'Соответствие'), ('ORDERING', 'Порядок'), ('IMAGE_CHOICE', 'Выбор изображения'), ('CASE_STUDY', 'Ситуационная задача')], max_length=24)),
                ('explanation', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='learning/questions/%Y/%m/')),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('manual_review_required', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.assessment')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'В процессе'), ('SUBMITTED', 'Отправлено'), ('AUTO_GRADED', 'Проверено автоматически'), ('WAITING_REVIEW', 'Ожидает проверки'), ('PASSED', 'Пройдено'), ('FAILED', 'Не пройдено'), ('EXPIRED', 'Время истекло')], default='IN_PROGRESS', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='learning.assessment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='learning.courseassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessment_attempts', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='attempts', to='learning.question')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500)),
                ('image', models.FileField(blank=True, upload_to='learning/answers/%Y/%m/')),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('match_key', models.CharField(blank=True, max_length=120)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.question')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('number_answer', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('review_comment', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.assessmentattempt')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='responses', to='learning.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='learning.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_response')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('assessment', 'employee', 'attempt_number'), name='unique_assessment_employee_attempt_number'),
        ),
    ]
