from django.core.management.base import BaseCommand
from access_control.models import Permission


PERMISSIONS = {
    "employee.view": "Просмотр сотрудников",
    "employee.manage": "Управление сотрудниками",
    "people.employee.view": "Просмотр справочника сотрудников",
    "people.invitation.manage": "Управление приглашениями сотрудников",
    "people.registration.manage": "Рассмотрение заявок на регистрацию",
    "people.account.manage": "Блокировка и разблокировка учётных записей",
    "people.employee.manage": "Управление сотрудниками",
    "people.directory.view": "Просмотр справочника сотрудников",
    "people.directory.view_extended": "Расширенный просмотр справочника",
    "people.directory.view_inactive": "Просмотр неактивных сотрудников",
    "people.profile.view_self": "Просмотр собственного профиля",
    "people.profile.update_self": "Изменение собственного профиля",
    "people.profile.manage": "Управление профилями сотрудников",
    "people.profile.view_sensitive": "Просмотр чувствительных полей профиля",
    "people.change_request.create_self": "Создание запроса на изменение своих данных",
    "people.change_request.view_self": "Просмотр своих запросов на изменение",
    "people.change_request.review": "Рассмотрение запросов на изменение данных",
    "people.change_request.apply": "Применение одобренных изменений данных",
    "people.change_request.manage": "Управление запросами на изменение данных",
    "people.assignment.view": "Просмотр организационных назначений",
    "people.assignment.manage": "Управление организационными назначениями",
    "people.organization.view": "Просмотр организационной структуры People",
    "people.organization.manage": "Управление организационной структурой People",
    "people.manager.view": "Просмотр иерархии руководителей",
    "people.manager.manage": "Управление иерархией руководителей",
    "people.group.view": "Просмотр команд сотрудников",
    "people.group.manage": "Управление командами сотрудников",
    "people.responsibility.view": "Просмотр зон ответственности",
    "people.responsibility.manage": "Управление зонами ответственности",
    "people.account.view": "Просмотр состояния учётной записи сотрудника",
    "people.performance.view": "Просмотр показателей сотрудника",
    "people.team.view": "Просмотр команд",
    "people.team.create": "Создание команд",
    "people.team.update": "Изменение команд",
    "people.team.manage": "Управление командами",
    "people.team.close": "Закрытие команд",
    "people.team_membership.view": "Просмотр участников команд",
    "people.team_membership.manage": "Управление участниками команд",
    "people.team_membership.view_history": "Просмотр истории команд",
    "organization.view": "Просмотр оргструктуры",
    "organization.manage": "Управление оргструктурой",
    "location.view": "Просмотр локаций",
    "location.manage": "Управление локациями",
    "functional_group.view": "Просмотр функциональных групп",
    "functional_group.manage": "Управление функциональными группами",
    "role.view": "Просмотр ролей",
    "role.manage": "Управление ролями",
    "audit.view": "Просмотр аудита",
    "task.create": "Создание задач",
    "task.view": "Просмотр задач",
    "task.edit": "Редактирование задач",
    "task.assign": "Публикация и назначение задач",
    "task.reassign": "Переназначение задач",
    "task.change_deadline": "Изменение срока задач",
    "task.start": "Начало выполнения задач",
    "task.pause": "Приостановка и возобновление задач",
    "task.complete": "Передача результата и завершение задач",
    "task.accept": "Приёмка задач",
    "task.reject": "Возврат задач с приёмки",
    "task.cancel": "Отмена задач",
    "task.reopen": "Повторное открытие задач",
    "task.admin": "Полное администрирование задач",
    "task.comment": "Комментирование задач",
    "task.comment_internal": "Внутренние комментарии задач",
    "task.comment_moderate": "Модерация комментариев задач",
    "task.attachment_add": "Добавление вложений задач",
    "task.attachment_delete": "Удаление вложений задач",
    "task.watch": "Самостоятельное наблюдение за задачами",
    "task.watcher_manage": "Управление наблюдателями задач",
    "task.checklist_manage": "Управление чек-листами задач",
    "task.checklist_complete": "Выполнение пунктов чек-листов",
    "checklist_template.view": "Просмотр шаблонов чек-листов",
    "checklist_template.manage": "Управление шаблонами чек-листов",
    "task_template.view": "Просмотр шаблонов задач",
    "task_template.manage": "Управление шаблонами задач",
    "task_template.use": "Создание задач из шаблонов",
    "task_recurrence.view": "Просмотр повторяющихся задач",
    "task_recurrence.manage": "Управление повторяющимися задачами",
    "task_recurrence.run": "Запуск и повтор генерации задач",
    "service_catalog.view": "Просмотр каталога услуг",
    "service_catalog.manage": "Управление каталогом услуг",
    "request_type.view": "Просмотр типов заявок",
    "request_type.manage": "Управление типами заявок",
    "request_type.publish": "Публикация схем типов заявок",
    "request.create": "Создание заявки",
    "request.create_for_others": "Создание заявок за других",
    "request.view": "Просмотр заявок",
    "request.edit": "Редактирование заявок",
    "request.assign": "Назначение заявок",
    "request.reassign": "Переназначение заявок",
    "request.start": "Начало обработки заявок",
    "request.wait": "Перевод заявок в ожидание",
    "request.resolve": "Решение заявок",
    "request.close": "Закрытие заявок",
    "request.reopen": "Повторное открытие заявок",
    "request.cancel": "Отмена заявок",
    "request.task_create": "Создание задач из заявок",
    "request.admin": "Администрирование заявок",
    "request_routing.view": "Просмотр маршрутизации заявок",
    "request_routing.manage": "Управление маршрутизацией заявок",
    "request.comment": "Публичные комментарии заявок",
    "request.comment_internal": "Внутренние заметки заявок",
    "request.comment_moderate": "Модерация комментариев заявок",
    "request.attachment_add": "Добавление вложений заявок",
    "request.attachment_internal": "Внутренние вложения заявок",
    "request.attachment_delete": "Удаление вложений заявок",
    "request.watch": "Наблюдение за заявками",
    "request.watcher_manage": "Управление наблюдателями заявок",
    "sla_calendar.view": "Просмотр бизнес-календарей",
    "sla_calendar.manage": "Управление бизнес-календарями",
    "sla_policy.view": "Просмотр SLA-политик",
    "sla_policy.manage": "Управление SLA-политиками",
    "sla_policy.publish": "Публикация SLA-политик",
    "sla_assignment_rule.view": "Просмотр правил SLA",
    "sla_assignment_rule.manage": "Управление правилами SLA",
    "sla.instance.view": "Просмотр runtime SLA",
    "sla.instance.manage": "Администрирование runtime SLA",
    "sla.escalation_policy.view": "Просмотр политик эскалации",
    "sla.escalation_policy.manage": "Управление политиками эскалации",
    "sla.escalation_policy.publish": "Публикация политик эскалации",
    "sla.escalation_binding.view": "Просмотр связей SLA и эскалаций",
    "sla.escalation_binding.manage": "Управление связями SLA и эскалаций",
    "sla.escalation_instance.view": "Просмотр runtime эскалаций",
    "sla.escalation_instance.manage": "Администрирование runtime эскалаций",
    "performance.view": "Просмотр собственных показателей эффективности",
    "performance.view_management": "Просмотр управленческой аналитики эффективности",
    "system.status.view": "Просмотр состояния системы и очередей",
}


class Command(BaseCommand):
    help = "Создаёт системный каталог permissions Phase 1.1A"

    def handle(self, *args, **options):
        for code, name in PERMISSIONS.items():
            Permission.objects.update_or_create(code=code, defaults={"name": name})
        self.stdout.write(self.style.SUCCESS(f"Permissions ready: {len(PERMISSIONS)}"))
