import uuid
from django.conf import settings
from django.db import models
class NotificationTemplate(models.Model):
    code=models.CharField(max_length=80,unique=True);name=models.CharField(max_length=160);title_template=models.CharField(max_length=240);body_template=models.TextField();allowed_variables=models.JSONField(default=list,blank=True);is_active=models.BooleanField(default=True,db_index=True);created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
class NotificationChannelTemplate(models.Model):
    template=models.ForeignKey(NotificationTemplate,on_delete=models.CASCADE,related_name="channel_templates");channel=models.CharField(max_length=20);subject_template=models.CharField(max_length=240,blank=True);body_template=models.TextField();is_active=models.BooleanField(default=True);created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["template","channel"],name="notification_unique_channel_template")]
class NotificationIntent(models.Model):
    class Status(models.TextChoices): PENDING="pending","Pending";MATERIALIZED="materialized","Materialized";FAILED="failed","Failed"
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);source_event_id=models.UUIDField(unique=True);event_type=models.CharField(max_length=120);reason=models.CharField(max_length=80);payload=models.JSONField(default=dict);status=models.CharField(max_length=20,choices=Status.choices,default=Status.PENDING,db_index=True);last_error=models.TextField(blank=True);created_at=models.DateTimeField(auto_now_add=True);processed_at=models.DateTimeField(null=True,blank=True)
class Notification(models.Model):
    class Type(models.TextChoices):
        TASK="task","Задача";CHECKLIST="checklist","Чек-лист";INCIDENT="incident","Инцидент";SENSOR="sensor","Датчик";SYSTEM="system","Система";SLA_ESCALATION="sla_escalation","SLA escalation";COURSE_ASSIGNED="course_assigned","Курс назначен";COURSE_DUE_SOON="course_due_soon","Срок курса приближается";COURSE_OVERDUE="course_overdue","Курс просрочен";COURSE_COMPLETED="course_completed","Курс завершён";ASSESSMENT_FAILED="assessment_failed","Тест не пройден";CERTIFICATE_ISSUED="certificate_issued","Сертификат выдан";CERTIFICATE_EXPIRING="certificate_expiring","Сертификат истекает";CERTIFICATE_EXPIRED="certificate_expired","Сертификат истёк";MATERIAL_ACK_REQUIRED="material_ack_required","Требуется ознакомление";MATERIAL_ACK_OVERDUE="material_ack_overdue","Ознакомление просрочено"
    class Priority(models.TextChoices): INFO="info","Информация";WARNING="warning","Предупреждение";CRITICAL="critical","Критическое"
    recipient=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="notifications");recipient_employee=models.ForeignKey("employees.Employee",on_delete=models.CASCADE,null=True,blank=True,related_name="notifications");intent=models.ForeignKey(NotificationIntent,on_delete=models.PROTECT,null=True,blank=True,related_name="notifications");template=models.ForeignKey(NotificationTemplate,on_delete=models.SET_NULL,null=True,blank=True,related_name="notifications");notification_type=models.CharField(max_length=40,choices=Type.choices);priority=models.CharField(max_length=20,choices=Priority.choices,default=Priority.INFO);title=models.CharField(max_length=240);message=models.TextField();entity_type=models.CharField(max_length=50,blank=True);entity_id=models.CharField(max_length=64,null=True,blank=True);action_url=models.CharField(max_length=500,blank=True);is_read=models.BooleanField(default=False,db_index=True);read_at=models.DateTimeField(null=True,blank=True);delivered_at=models.DateTimeField(null=True,blank=True);telegram_status=models.CharField(max_length=20,default="pending");is_demo=models.BooleanField(default=False);created_at=models.DateTimeField(auto_now_add=True)
    class Meta: ordering=["is_read","-created_at"];constraints=[models.UniqueConstraint(fields=["intent","recipient_employee"],name="notification_unique_intent_recipient")];indexes=[models.Index(fields=["recipient_employee","is_read","created_at"])]
class NotificationDelivery(models.Model):
    class Channel(models.TextChoices): IN_APP="in_app","In-app";TELEGRAM="telegram","Telegram";EMAIL="email","Email"
    class Status(models.TextChoices): PENDING="pending","Pending";PROCESSING="processing","Processing";DELIVERED="delivered","Delivered";RETRY="retry","Retry";FAILED="failed","Failed";SUPPRESSED="suppressed","Suppressed";UNKNOWN="unknown","Unknown"
    notification=models.ForeignKey(Notification,on_delete=models.CASCADE,related_name="deliveries");channel=models.CharField(max_length=20,choices=Channel.choices,default=Channel.IN_APP);status=models.CharField(max_length=20,choices=Status.choices,default=Status.PENDING,db_index=True);attempts=models.PositiveIntegerField(default=0);next_attempt_at=models.DateTimeField(null=True,blank=True,db_index=True);delivered_at=models.DateTimeField(null=True,blank=True);processing_started_at=models.DateTimeField(null=True,blank=True);provider_started_at=models.DateTimeField(null=True,blank=True);last_error=models.TextField(blank=True);last_error_code=models.CharField(max_length=80,blank=True,db_index=True);provider_message_id=models.CharField(max_length=160,blank=True);provider_metadata=models.JSONField(default=dict,blank=True);routing_snapshot=models.JSONField(default=dict,blank=True);created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
    class Meta: constraints=[models.UniqueConstraint(fields=["notification","channel"],name="notification_unique_delivery_channel")]
class NotificationDeliveryAttempt(models.Model):
    delivery=models.ForeignKey(NotificationDelivery,on_delete=models.CASCADE,related_name="attempt_log");attempt_number=models.PositiveIntegerField();successful=models.BooleanField(default=False);outcome=models.CharField(max_length=20,default="failed");error=models.TextField(blank=True);error_code=models.CharField(max_length=80,blank=True);provider_metadata=models.JSONField(default=dict,blank=True);created_at=models.DateTimeField(auto_now_add=True)
    class Meta: constraints=[models.UniqueConstraint(fields=["delivery","attempt_number"],name="notification_unique_delivery_attempt")]
class NotificationPreference(models.Model):
    employee=models.ForeignKey("employees.Employee",on_delete=models.CASCADE,related_name="notification_preferences");reason=models.CharField(max_length=80,default="*");channel=models.CharField(max_length=20,choices=NotificationDelivery.Channel.choices,default=NotificationDelivery.Channel.IN_APP);enabled=models.BooleanField(default=True);created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
    class Meta: constraints=[models.UniqueConstraint(fields=["employee","reason","channel"],name="notification_unique_preference")]
class NotificationQuietHours(models.Model):
    employee=models.OneToOneField("employees.Employee",on_delete=models.CASCADE,related_name="notification_quiet_hours");enabled=models.BooleanField(default=False);timezone=models.CharField(max_length=64,default="UTC");starts_at=models.TimeField();ends_at=models.TimeField();created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
class TelegramAccount(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);employee=models.ForeignKey("employees.Employee",on_delete=models.PROTECT,related_name="telegram_accounts");telegram_user_id=models.BigIntegerField();telegram_chat_id=models.BigIntegerField();username=models.CharField(max_length=80,blank=True);first_name=models.CharField(max_length=120,blank=True);last_name=models.CharField(max_length=120,blank=True);is_active=models.BooleanField(default=True,db_index=True);linked_at=models.DateTimeField();unlinked_at=models.DateTimeField(null=True,blank=True);delivery_disabled_at=models.DateTimeField(null=True,blank=True);last_success_at=models.DateTimeField(null=True,blank=True);last_failure_at=models.DateTimeField(null=True,blank=True);last_failure_code=models.CharField(max_length=80,blank=True);created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
    class Meta:constraints=[models.UniqueConstraint(fields=["employee"],condition=models.Q(is_active=True),name="telegram_one_active_per_employee"),models.UniqueConstraint(fields=["telegram_user_id"],condition=models.Q(is_active=True),name="telegram_one_active_per_user")]
class TelegramLinkToken(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);employee=models.ForeignKey("employees.Employee",on_delete=models.CASCADE,related_name="telegram_link_tokens");token_hash=models.CharField(max_length=64,unique=True);expires_at=models.DateTimeField();used_at=models.DateTimeField(null=True,blank=True);revoked_at=models.DateTimeField(null=True,blank=True);created_at=models.DateTimeField(auto_now_add=True)
class TelegramWebhookEvent(models.Model):
    update_id=models.BigIntegerField(primary_key=True);command=models.CharField(max_length=32,blank=True);telegram_user_id=models.BigIntegerField(null=True,blank=True);status=models.CharField(max_length=32,default="processing");result_code=models.CharField(max_length=80,blank=True);processed_at=models.DateTimeField(null=True,blank=True);created_at=models.DateTimeField(auto_now_add=True)
