# Generated by Django 5.1.5 on 2026-08-15 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_initial'),
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('organizations', '0002_legalentity_location_orgunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_anonymous_employee', models.BooleanField(default=False)),
                ('allow_self_service', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_request_types', to='employees.employee')),
            ],
            options={
                'ordering': ['position', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('choice', 'Choice'), ('multi_choice', 'Multiple choice'), ('employee', 'Employee'), ('org_unit', 'Org unit'), ('legal_entity', 'Legal entity'), ('location', 'Location'), ('file', 'File')], max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='service_requests.requesttype')),
            ],
            options={
                'ordering': ['position', 'key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestTypeAccessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('legal_entity', 'Legal entity'), ('org_unit', 'Org unit'), ('location', 'Location'), ('role', 'Role')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.orgunit')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='service_requests.requesttype')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='access_control.role')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestTypeSchemaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_request_schemas', to='employees.employee')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schema_versions', to='service_requests.requesttype')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='requesttype',
            name='current_schema_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_type', to='service_requests.requesttypeschemaversion'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='organizations.location')),
                ('owner_functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_services', to='employees.functionalgroup')),
                ('owner_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_services', to='organizations.orgunit')),
            ],
            options={
                'ordering': ['position', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='requesttype',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_types', to='service_requests.service'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='service_requests.servicecategory')),
            ],
            options={
                'ordering': ['position', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service_requests.servicecategory'),
        ),
        migrations.CreateModel(
            name='RequestFieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='service_requests.requestfielddefinition')),
            ],
            options={
                'ordering': ['position', 'value', 'id'],
                'constraints': [models.UniqueConstraint(fields=('field', 'value'), name='unique_request_field_option')],
            },
        ),
        migrations.AddConstraint(
            model_name='requestfielddefinition',
            constraint=models.UniqueConstraint(fields=('request_type', 'key'), name='unique_request_field_key'),
        ),
        migrations.AddConstraint(
            model_name='requesttypeschemaversion',
            constraint=models.UniqueConstraint(fields=('request_type', 'version'), name='unique_request_schema_version'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='service_category_parent_not_self'),
        ),
    ]
