# Generated by Django 5.1.5 on 2026-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_initial'),
        ('organizations', '0002_legalentity_location_orgunit'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requesttypeaccessrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('legal_entity__isnull', True), ('location__isnull', True), ('org_unit__isnull', True), ('role__isnull', True), ('scope_type', 'global')), models.Q(('legal_entity__isnull', False), ('location__isnull', True), ('org_unit__isnull', True), ('role__isnull', True), ('scope_type', 'legal_entity')), models.Q(('legal_entity__isnull', True), ('location__isnull', True), ('org_unit__isnull', False), ('role__isnull', True), ('scope_type', 'org_unit')), models.Q(('legal_entity__isnull', True), ('location__isnull', False), ('org_unit__isnull', True), ('role__isnull', True), ('scope_type', 'location')), models.Q(('legal_entity__isnull', True), ('location__isnull', True), ('org_unit__isnull', True), ('role__isnull', False), ('scope_type', 'role')), _connector='OR'), name='request_access_rule_exact_target'),
        ),
    ]
