# Generated by Django 5.1.5 on 2026-08-27 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('organizations', '0002_legalentity_location_orgunit'),
        ('service_requests', '0002_requesttypeaccessrule_request_access_rule_exact_target'),
        ('work_tasks', '0003_alter_task_source_type_taskrecurrencerule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestNumberSequence',
            fields=[
                ('key', models.CharField(default='request', max_length=32, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='requesttype',
            name='task_completion_policy',
            field=models.CharField(choices=[('none', 'No task restriction'), ('all_execution_tasks_terminal', 'All execution tasks terminal'), ('all_execution_tasks_completed', 'All execution tasks completed')], default='none', max_length=40),
        ),
        migrations.CreateModel(
            name='RequestRoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.orgunit')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='service_requests.requesttype')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_routing_rules', to='employees.assignmenttarget')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=32, unique=True)),
                ('subject', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('waiting_requester', 'Waiting requester'), ('waiting_external', 'Waiting external'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=24)),
                ('routing_unresolved', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, max_length=64)),
                ('resolution_comment', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to='employees.employee')),
                ('assigned_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to='employees.assignmenttarget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.servicecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_requests', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='organizations.orgunit')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.requesttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='employees.employee')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_requests', to='employees.employee')),
                ('responsible_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_requests', to='employees.assignmenttarget')),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.requesttypeschemaversion')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.service')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_assignment_changes', to='employees.employee')),
                ('new_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_request_assignments', to='employees.employee')),
                ('new_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_request_assignments', to='employees.assignmenttarget')),
                ('old_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_request_assignments', to='employees.employee')),
                ('old_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_request_assignments', to='employees.assignmenttarget')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='service_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestFieldRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_field_revisions', to='employees.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_revisions', to='service_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('choice', 'Choice'), ('multi_choice', 'Multiple choice'), ('employee', 'Employee'), ('org_unit', 'Org unit'), ('legal_entity', 'Legal entity'), ('location', 'Location'), ('file', 'File')], max_length=24)),
                ('label', models.CharField(max_length=200)),
                ('value_json', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_values', to='service_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('duplicate_of', 'Duplicate of'), ('related_to', 'Related to')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='service_requests.servicerequest')),
                ('to_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='service_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('waiting_requester', 'Waiting requester'), ('waiting_external', 'Waiting external'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=24)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('waiting_requester', 'Waiting requester'), ('waiting_external', 'Waiting external'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_status_changes', to='employees.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('execution', 'Execution'), ('follow_up', 'Follow-up')], default='execution', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_request_task_links', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='service_requests.servicerequest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_links', to='work_tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestWaitingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waiting_type', models.CharField(choices=[('waiting_requester', 'Requester'), ('waiting_external', 'External')], max_length=24)),
                ('comment', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_request_waits', to='employees.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiting_periods', to='service_requests.servicerequest')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_request_waits', to='employees.employee')),
            ],
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['request_type'], name='service_req_request_f84aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['service'], name='service_req_service_04f656_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['requester'], name='service_req_request_dbdd52_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_employee'], name='service_req_assigne_4fd6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['responsible_employee'], name='service_req_respons_7e67fe_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['org_unit'], name='service_req_org_uni_c09af5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['legal_entity'], name='service_req_legal_e_7460a8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['location'], name='service_req_locatio_7dd0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='service_req_status_0ae749_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestfieldvalue',
            constraint=models.UniqueConstraint(fields=('request', 'field_key'), name='unique_request_field_value'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestrelation',
            constraint=models.UniqueConstraint(fields=('from_request', 'to_request', 'relation_type'), name='unique_request_relation'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestrelation',
            constraint=models.CheckConstraint(condition=models.Q(('from_request', models.F('to_request')), _negated=True), name='request_relation_not_self'),
        ),
        migrations.AddConstraint(
            model_name='servicerequesttask',
            constraint=models.UniqueConstraint(fields=('request', 'task'), name='unique_request_task_link'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestwaitingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('request',), name='one_active_wait_per_request'),
        ),
    ]
