# Generated by Django 5.1.5 on 2026-08-27 09:28

import django.db.models.deletion
import service_requests.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('service_requests', '0003_requestnumbersequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], db_index=True, default='public', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_comments', to='employees.employee')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_request_comments', to='employees.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestCommentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mention_records', to='service_requests.servicerequestcomment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_comment_mentions', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestCommentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='service_requests.servicerequestcomment')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_comment_revisions', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestWatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_request_watchers', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watched_service_requests', to='employees.employee')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_request_watchers', to='employees.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watcher_records', to='service_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=service_requests.models.request_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], db_index=True, default='public', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_request_attachments', to='employees.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='service_requests.servicerequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_request_attachments', to='employees.employee')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['request', 'visibility', 'created_at'], name='service_req_request_d6cbdc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequestcomment',
            index=models.Index(fields=['request', 'visibility', 'created_at'], name='service_req_request_dde65b_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestcommentmention',
            constraint=models.UniqueConstraint(fields=('comment', 'employee'), name='unique_request_comment_mention'),
        ),
        migrations.AddIndex(
            model_name='servicerequestwatcher',
            index=models.Index(fields=['request', 'employee', 'removed_at'], name='service_req_request_8d8e44_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestwatcher',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('request', 'employee'), name='unique_active_request_watcher'),
        ),
    ]
