# Generated by Django 5.1.5 on 2026-08-31 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('organizations', '0002_legalentity_location_orgunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('employee', 'Employee'), ('org_unit', 'Organisation unit'), ('location', 'Location'), ('legal_entity', 'Legal entity'), ('overview', 'Overview')], max_length=24)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('period_from', models.DateTimeField()),
                ('period_to', models.DateTimeField()),
                ('reporting_timezone', models.CharField(max_length=64)),
                ('metric_code', models.CharField(max_length=80)),
                ('calculation_version', models.CharField(default='1.5.0', max_length=32)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='measured', max_length=24)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'period_from', 'period_to'], name='perf_aggregate_lookup')],
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'subject_id', 'period_from', 'period_to', 'reporting_timezone', 'metric_code', 'calculation_version'), name='performance_aggregate_slice')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduplication_key', models.CharField(max_length=240, unique=True)),
                ('period_from', models.DateTimeField()),
                ('period_to', models.DateTimeField()),
                ('reporting_timezone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='perf_recalc_claim')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_key', models.CharField(max_length=240)),
                ('calculation_version', models.CharField(default='1.5.0', max_length=32)),
                ('source_domain', models.CharField(max_length=24)),
                ('source_id', models.UUIDField()),
                ('metric_code', models.CharField(max_length=80)),
                ('attribution_role', models.CharField(choices=[('responsible', 'Responsible'), ('executor', 'Executor'), ('requester', 'Requester'), ('reviewer', 'Reviewer')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=4, default=1, max_digits=20)),
                ('sample_size', models.PositiveIntegerField(default=1)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_facts', to='employees.employee')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.orgunit')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'metric_code', 'occurred_at'], name='perf_fact_emp_metric_time'), models.Index(fields=['source_domain', 'source_id'], name='perf_fact_source'), models.Index(fields=['org_unit', 'occurred_at'], name='perf_fact_org_time')],
                'constraints': [models.UniqueConstraint(fields=('fact_key', 'calculation_version'), name='performance_fact_version_key')],
            },
        ),
        migrations.CreateModel(
            name='ScoringPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('weights', models.JSONField(default=dict)),
                ('thresholds', models.JSONField(default=dict)),
                ('minimum_samples', models.PositiveIntegerField(default=5)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='performance.scoringpolicy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('policy', 'version'), name='performance_scoring_policy_version')],
            },
        ),
    ]
