# Generated by Django 5.1.5 on 2026-08-31 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEventReceipt',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recalculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_receipts', to='performance.performancerecalculation')),
            ],
        ),
    ]
