# Generated by Django 5.1.5 on 2026-09-09 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_outboxevent_last_error_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCreation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('connection_id', models.SlugField()),
                ('organization_id', models.UUIDField()),
                ('card_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(default='running', max_length=24)),
                ('stage', models.CharField(default='preflight', max_length=40)),
                ('completed_categories', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['running', 'succeeded', 'needs_review'])), fields=('connection_id', 'organization_id', 'card_digest'), name='iiko_card_creation_reservation')],
            },
        ),
    ]
