# Generated by Django 5.1.5 on 2026-09-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.SlugField()),
                ('organization_id', models.UUIDField()),
                ('field', models.CharField(choices=[('department', 'Подразделение'), ('legalEntity', 'Юридическое лицо'), ('cardType', 'Тип карты'), ('approval', 'Согласование')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('external_id', models.UUIDField()),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('connection_id', 'organization_id', 'external_id'), name='iiko_category_scope_id')],
            },
        ),
    ]
