# Generated by Django 5.1.5 on 2026-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0003_seed_card_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcreation',
            name='error_correlation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardcreation',
            name='error_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
