# Generated by Django 5.1.5 on 2026-09-09 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0004_cardcreation_error_correlation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.SlugField()),
                ('organization_id', models.UUIDField()),
                ('customer_id', models.UUIDField()),
                ('name_digest', models.CharField(db_index=True, max_length=64)),
                ('observed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cardcreation',
            name='iiko_card_creation_reservation',
        ),
        migrations.AddField(
            model_name='cardcreation',
            name='previous_customer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardcreation',
            name='reservation_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='cardcreation',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation_active', True), ('status__in', ['running', 'succeeded', 'needs_review'])), fields=('connection_id', 'organization_id', 'card_digest'), name='iiko_card_creation_reservation'),
        ),
        migrations.AddConstraint(
            model_name='knownguest',
            constraint=models.UniqueConstraint(fields=('connection_id', 'organization_id', 'customer_id'), name='iiko_known_guest_scope'),
        ),
    ]
