# Generated by Django 5.1.5 on 2026-09-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0005_knownguest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcreation',
            name='error_diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
