# Generated by Django 5.1.5 on 2026-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0006_cardcreation_error_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcreation',
            name='topup_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cardcreation',
            name='topup_balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='cardcreation',
            name='topup_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardcreation',
            name='topup_wallet_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
