# Generated by Django 5.1.5 on 2026-08-03 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Температура'), ('humidity', 'Влажность'), ('door', 'Открытие двери'), ('co2', 'CO₂'), ('pressure', 'Давление'), ('power', 'Питание'), ('signal', 'Сигнал'), ('battery', 'Батарея'), ('universal', 'Универсальный')], max_length=24)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('equipment', models.CharField(blank=True, max_length=180)),
                ('unit', models.CharField(max_length=20)),
                ('allowed_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('critical_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('critical_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_deviation_minutes', models.PositiveIntegerField(default=15)),
                ('transmission_interval_seconds', models.PositiveIntegerField(default=300)),
                ('installed_at', models.DateField()),
                ('serviced_at', models.DateField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(default=100)),
                ('signal_quality', models.PositiveSmallIntegerField(default=100)),
                ('state', models.CharField(choices=[('normal', 'Норма'), ('warning', 'Предупреждение'), ('critical', 'Критическое отклонение'), ('offline', 'Нет связи'), ('maintenance', 'Обслуживание')], default='normal', max_length=20)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='organizations.facility')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='organizations.zone')),
            ],
            options={
                'ordering': ['facility', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('normal', 'Норма'), ('warning', 'Предупреждение'), ('critical', 'Критическое отклонение'), ('offline', 'Нет связи'), ('maintenance', 'Обслуживание')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_value', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sensors.sensor')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='SensorHourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('minimum', models.DecimalField(decimal_places=3, max_digits=12)),
                ('maximum', models.DecimalField(decimal_places=3, max_digits=12)),
                ('average', models.DecimalField(decimal_places=3, max_digits=12)),
                ('measurement_count', models.PositiveIntegerField()),
                ('outside_norm_seconds', models.PositiveIntegerField(default=0)),
                ('offline_seconds', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_aggregates', to='sensors.sensor')),
            ],
            options={
                'ordering': ['hour'],
                'constraints': [models.UniqueConstraint(fields=('sensor', 'hour'), name='unique_sensor_hour')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('level', models.CharField(choices=[('normal', 'Норма'), ('warning', 'Предупреждение'), ('critical', 'Критическое отклонение'), ('offline', 'Нет связи'), ('maintenance', 'Обслуживание')], max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor', 'recorded_at'], name='sensors_sen_sensor__e1a858_idx')],
            },
        ),
    ]
