import React, { useEffect, useRef, useState } from "react";
import { Page, WorkApiError, workDownload, workRequest } from "./workApi";

type Navigate = (path: string) => void;
type Project = { id:string; number:string; name:string; description:string; goal:string; expected_result:string; manager:string|null; manager_name:string|null; customer:string|null; org_unit:string|null; status:string; version:number; planned_start_at:string|null; planned_end_at:string|null; is_archived:boolean };
type Stage = { id:string; name:string; position:number; planned_start_at:string|null; planned_end_at:string|null };
type Milestone = { id:string; name:string; due_at:string|null; required:boolean; confirmed_at:string|null; criterion:string };
type Task = { id:string; number:string; title:string; status:string; version:number; due_at:string|null; is_overdue:boolean; responsible_employee_display?:string|null; responsible_target_display?:string|null; executor_employee_display?:string|null; project?:{stage_id:string|null} };
type TaskPage = Page<Task>&{stage_counts:Record<string,number>;responsible_options:{id:string;display_name:string}[]};
type Employee = { id:string; display_name:string };
type Member = { id:string; employee:string; employee_name:string; role:string };
type Attachment = { id:string; original_filename:string; size:number };
type Comment = { id:string; author_name:string; body:string; created_at:string };
type Tab = "tasks"|"overview"|"team"|"files"|"discussion";
type Mode = "list"|"board"|"timeline";
type Panel = "create"|"link"|"template"|"settings"|"history"|"member"|null;

const root="/projects/";
const get=<T,>(path:string)=>workRequest<T>(root+path);
const post=<T,>(path:string,data:unknown,key?:string)=>workRequest<T>(root+path,{method:"POST",body:JSON.stringify(data),headers:key?{"Idempotency-Key":key}:{}});
const statusName:Record<string,string>={draft:"Черновик",active:"Активен",on_hold:"Приостановлен",completed:"Завершён",cancelled:"Отменён",review:"На приёмке",waiting:"Ожидание",in_progress:"В работе",open:"Открыта"};
const roleName:Record<string,string>={manager:"Руководитель проекта",member:"Участник",observer:"Наблюдатель"};
const actionName:Record<string,string>={created:"Проект создан","project.created":"Проект создан",updated:"Параметры изменены","project.updated":"Параметры проекта изменены",started:"Проект запущен","project.started":"Проект запущен",held:"Проект приостановлен","project.held":"Проект приостановлен",completed:"Проект завершён","project.completed":"Проект завершён",cancelled:"Проект отменён","project.cancelled":"Проект отменён",reopened:"Проект открыт повторно","project.reopened":"Проект открыт повторно",archived:"Проект отправлен в архив","project.archived":"Проект отправлен в архив",unarchived:"Проект возвращён из архива","project.unarchived":"Проект возвращён из архива","project.stage.created":"Этап создан","project.stage.updated":"Этап изменён","project.milestone.created":"Контрольная точка создана","project.milestone.updated":"Контрольная точка изменена",linked:"Задача привязана",unlinked:"Задача отвязана",moved:"Задача перемещена"};
const date=(value:string|null)=>value?new Date(value).toLocaleDateString("ru-RU"):"—";
const inputDate=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
const requestKey=()=>{const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,x=>x.toString(16).padStart(2,"0")).join("");return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;};
const currentState=()=>{const q=new URLSearchParams(window.location.search);const tab=(q.get("tab")||"tasks") as Tab;const view=(q.get("view")||"list") as Mode;const page=Math.max(1,Number(q.get("page")||1)||1);return {tab:["tasks","overview","team","files","discussion"].includes(tab)?tab:"tasks" as Tab,mode:["list","board","timeline"].includes(view)?view:"list" as Mode,search:q.get("search")||"",status:q.get("status")||"",responsible:q.get("responsible")||"",page};};

function ErrorBanner({error,onClose}:{error:unknown;onClose:()=>void}){const value=error instanceof WorkApiError?error.message:error instanceof Error?error.message:"Не удалось выполнить действие.";return <div className="project-error" role="alert"><strong>{value}</strong><button onClick={onClose}>Закрыть</button></div>;}

export function ProjectDetail({id,navigate}:{id:string;navigate:Navigate}){
  const initial=currentState();
  const [tab,setTab]=useState<Tab>(initial.tab);const [mode,setMode]=useState<Mode>(initial.mode);const [panel,setPanelState]=useState<Panel>(null);
  const [project,setProject]=useState<Project|null>(null);const [stages,setStages]=useState<Stage[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [taskPage,setTaskPage]=useState<TaskPage|null>(null);const [taskPageNo,setTaskPageNo]=useState(initial.page);const [counters,setCounters]=useState<any>(null);
  const [milestones,setMilestones]=useState<Milestone[]>([]);const [members,setMembers]=useState<Member[]>([]);const [attachments,setAttachments]=useState<Attachment[]>([]);const [comments,setComments]=useState<Comment[]>([]);const [history,setHistory]=useState<{project:{action:string;created_at:string}[];links:{action:string;task_id:string;created_at:string}[]}|null>(null);
  const [people,setPeople]=useState<Employee[]>([]);const [targets,setTargets]=useState<{id:string;display_name:string}[]>([]);const [templates,setTemplates]=useState<{id:string;name:string}[]>([]);const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const [success,setSuccess]=useState("");
  const [search,setSearch]=useState(initial.search);const [statusFilter,setStatusFilter]=useState(initial.status);const [responsibleFilter,setResponsibleFilter]=useState(initial.responsible);const [collapsed,setCollapsed]=useState<Record<string,boolean>>({none:true});const [showStageCreate,setShowStageCreate]=useState(false);
  const [taskTitle,setTaskTitle]=useState("");const [taskDescription,setTaskDescription]=useState("");const [taskStage,setTaskStage]=useState("");const [taskDue,setTaskDue]=useState("");const [taskPriority,setTaskPriority]=useState("normal");const [taskAcceptance,setTaskAcceptance]=useState("none");const [responsibleTarget,setResponsibleTarget]=useState("");const [executorTarget,setExecutorTarget]=useState("");const [taskKey,setTaskKey]=useState(requestKey);
  const [linkSearch,setLinkSearch]=useState("");const [linkOptions,setLinkOptions]=useState<Task[]>([]);const [selectedTask,setSelectedTask]=useState("");const [template,setTemplate]=useState("");
  const [member,setMember]=useState("");const [memberRole,setMemberRole]=useState("member");const [comment,setComment]=useState("");const [mention,setMention]=useState("");const [stageName,setStageName]=useState("");
  const [edit,setEdit]=useState({name:"",description:"",goal:"",result:"",manager:"",customer:"",orgUnit:"",start:"",end:""});
  const returnFocus=useRef<HTMLElement|null>(null);const loadSequence=useRef(0);

  const loadBase=async()=>{const sequence=++loadSequence.current;try{const q=new URLSearchParams({page:String(taskPageNo)});if(search.trim())q.set("search",search.trim());if(statusFilter)q.set("status",statusFilter);if(responsibleFilter)q.set("responsible",responsibleFilter);const [p,s,t,c]=await Promise.all([get<Project>(`${id}/`),get<Stage[]>(`${id}/stages/`),get<TaskPage>(`${id}/tasks/?${q}`),get<any>(`${id}/counters/`)]);if(sequence!==loadSequence.current)return;setProject(p);setStages(s);setTasks(t.results);setTaskPage(t);setCounters(c);setEdit({name:p.name,description:p.description||"",goal:p.goal||"",result:p.expected_result||"",manager:p.manager||"",customer:p.customer||"",orgUnit:p.org_unit||"",start:inputDate(p.planned_start_at),end:inputDate(p.planned_end_at)});setError(undefined);}catch(e){if(sequence===loadSequence.current)setError(e);}};
  useEffect(()=>{const timer=setTimeout(()=>void loadBase(),search?250:0);return()=>clearTimeout(timer);},[id,taskPageNo,search,statusFilter,responsibleFilter]);
  useEffect(()=>{workRequest<Page<Employee>>("/employees/").then(x=>setPeople(x.results)).catch(()=>{});workRequest<Page<{id:string;display_name:string}>>("/assignment-targets/").then(x=>setTargets(x.results)).catch(()=>{});workRequest<Page<{id:string;name:string}>>("/task-templates/").then(x=>setTemplates(x.results)).catch(()=>{});},[]);
  useEffect(()=>{const sync=()=>{const s=currentState();setTab(s.tab);setMode(s.mode);setSearch(s.search);setStatusFilter(s.status);setResponsibleFilter(s.responsible);setTaskPageNo(s.page);};window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[]);
  useEffect(()=>{if(tab==="overview"||mode==="timeline")get<Milestone[]>(`${id}/milestones/`).then(setMilestones).catch(setError);if(tab==="team")get<Member[]>(`${id}/members/`).then(setMembers).catch(setError);if(tab==="files")get<Attachment[]>(`${id}/attachments/`).then(setAttachments).catch(setError);if(tab==="discussion")get<Comment[]>(`${id}/comments/`).then(setComments).catch(setError);},[tab,mode,id]);
  useEffect(()=>{if(panel==="history"&&!history)get<any>(`${id}/history/`).then(setHistory).catch(setError);},[panel,id]);
  useEffect(()=>{if(!linkSearch.trim()){setLinkOptions([]);return;}const timer=setTimeout(()=>workRequest<Page<Task>>(`/tasks/?search=${encodeURIComponent(linkSearch)}`).then(x=>setLinkOptions(x.results)).catch(()=>setLinkOptions([])),250);return()=>clearTimeout(timer);},[linkSearch]);

  const taskQuery=(nextTab=tab,nextMode=mode,nextSearch=search,nextStatus=statusFilter,nextResponsible=responsibleFilter,nextPage=taskPageNo)=>{const q=new URLSearchParams();if(nextTab!=="tasks")q.set("tab",nextTab);if(nextTab==="tasks"&&nextMode!=="list")q.set("view",nextMode);if(nextTab==="tasks"){if(nextSearch)q.set("search",nextSearch);if(nextStatus)q.set("status",nextStatus);if(nextResponsible)q.set("responsible",nextResponsible);if(nextPage>1)q.set("page",String(nextPage));}return q;};
  const updateUrl=(nextTab:Tab,nextMode=mode)=>{const q=taskQuery(nextTab,nextMode);window.history.pushState({},"",`${window.location.pathname}${q.size?`?${q}`:""}`);setTab(nextTab);setMode(nextMode);};
  const updateFilters=(nextSearch:string,nextStatus:string,nextResponsible:string)=>{const q=taskQuery("tasks",mode,nextSearch,nextStatus,nextResponsible,1);window.history.replaceState({},"",`${window.location.pathname}${q.size?`?${q}`:""}`);setSearch(nextSearch);setStatusFilter(nextStatus);setResponsibleFilter(nextResponsible);setTaskPageNo(1);};
  const changePage=(page:number)=>{const q=taskQuery("tasks",mode,search,statusFilter,responsibleFilter,page);window.history.pushState({},"",`${window.location.pathname}${q.size?`?${q}`:""}`);setTaskPageNo(page);};
  const dirty=Boolean(taskTitle||taskDescription||taskDue||responsibleTarget||executorTarget||selectedTask||template);
  const openPanel=(value:Panel,event?:React.SyntheticEvent)=>{returnFocus.current=event?.currentTarget as HTMLElement||null;setPanelState(value);setError(undefined);};
  const closePanel=(force=false)=>{if(!force&&dirty&&["create","link","template"].includes(panel||"")&&!window.confirm("Закрыть форму? Введённые данные будут потеряны."))return;setPanelState(null);setTimeout(()=>returnFocus.current?.focus(),0);};
  const action=async(path:string,data:unknown,key?:string,method:"POST"|"PATCH"="POST")=>{setBusy(true);try{if(method==="PATCH")await workRequest(`${root}${id}/${path}/`,{method,body:JSON.stringify(data)});else await post(`${id}/${path}/`,data,key);await loadBase();return true;}catch(e){setError(e);return false;}finally{setBusy(false);}};
  if(error&&!project)return <main className="project-page"><ErrorBanner error={error} onClose={loadBase}/></main>;if(!project)return <main className="project-page">Загружаем проект…</main>;
  const editable=!project.is_archived&&!["completed","cancelled"].includes(project.status);const responsibleOf=(task:Task)=>task.responsible_employee_display||task.responsible_target_display||"";
  const visibleTasks=tasks;
  const groups=[...stages.map(s=>({id:s.id,name:s.name,stage:s,tasks:visibleTasks.filter(t=>t.project?.stage_id===s.id),count:taskPage?.stage_counts?.[s.id]||0})),{id:"none",name:"Без этапа",stage:null,tasks:visibleTasks.filter(t=>!t.project?.stage_id),count:taskPage?.stage_counts?.none||0}];
  const taskCommand=async(task:Task,command:"move-stage"|"unlink-task",stageId?:string)=>{try{const current=await workRequest<any>(`/tasks/${task.id}/`);const reason=command==="unlink-task"?window.prompt("Причина отвязки задачи"):"";if(command==="unlink-task"&&!reason?.trim())return;await action(command,{project_version:project.version,task_version:current.version,task:task.id,...(command==="move-stage"?{stage:stageId||null}:{reason})});}catch(e){setError(e);}};
  const boardMove=async(task:Task,target:string)=>{const commands:Record<string,string>={"draft:open":"publish","open:in_progress":"start","in_progress:waiting":"pause","waiting:in_progress":"resume","in_progress:review":"complete","in_progress:completed":"complete","review:completed":"accept","review:in_progress":"reject","completed:in_progress":"reopen","draft:cancelled":"cancel","open:cancelled":"cancel","in_progress:cancelled":"cancel","waiting:cancelled":"cancel","review:cancelled":"cancel"};const command=commands[`${task.status}:${target}`];if(!command){setError(new Error("Для этого перехода откройте задачу Work и выберите разрешённую операцию."));return;}const payload:Record<string,unknown>={version:task.version};if(command==="pause"){const reason=window.prompt("Причина ожидания: waiting_requester, waiting_external, waiting_material, waiting_approval или waiting_other","waiting_approval");if(!reason)return;payload.reason=reason;if(reason==="waiting_other"){const comment=window.prompt("Комментарий к ожиданию");if(!comment?.trim())return;payload.comment=comment;}}if(["reject","reopen","cancel"].includes(command)){const reason=window.prompt("Причина перехода задачи Work");if(!reason?.trim())return;payload.reason=reason;}try{await workRequest(`/tasks/${task.id}/${command}/`,{method:"POST",body:JSON.stringify(payload)});await loadBase();}catch(e){setError(e);}};
  const taskCard=(task:Task)=><article key={task.id} className={`project-task${task.is_overdue?" overdue":""}`} role="button" tabIndex={0} draggable={mode==="board"} onDragStart={e=>e.dataTransfer.setData("text/plain",task.id)} onClick={()=>navigate(`/tasks/${task.id}`)} onKeyDown={e=>{if(e.key==="Enter")navigate(`/tasks/${task.id}`);}}><div><strong>{task.title}</strong><small>{task.number}</small></div><span data-label="Статус">{statusName[task.status]||task.status}</span><span data-label="Ответственный">{responsibleOf(task)||"Ответственный не назначен"}</span><span data-label="Срок">{task.due_at?date(task.due_at):"Без срока"}</span>{editable&&mode==="list"&&<details className="project-task-menu" onClick={e=>e.stopPropagation()}><summary aria-label={`Действия задачи ${task.number}`}>⋯</summary><div className="project-menu"><label>Этап<select aria-label={`Этап задачи ${task.number}`} value={task.project?.stage_id||""} onChange={e=>taskCommand(task,"move-stage",e.target.value)}><option value="">Без этапа</option>{stages.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button onClick={()=>taskCommand(task,"unlink-task")}>Удалить связь с проектом</button></div></details>}</article>;
  const resetTask=()=>{setTaskTitle("");setTaskDescription("");setTaskDue("");setTaskPriority("normal");setTaskAcceptance("none");setResponsibleTarget("");setExecutorTarget("");setTaskStage("");setTaskKey(requestKey());};
  const createTask=async()=>{if(!taskTitle.trim())return;const ok=await action("create-task",{project_version:project.version,title:taskTitle.trim(),description:taskDescription,stage:taskStage||null,due_at:taskDue?new Date(taskDue).toISOString():null,priority:taskPriority,acceptance_policy:taskAcceptance,responsible_target:responsibleTarget||null,executor_target:executorTarget||null},taskKey);if(ok){resetTask();closePanel(true);setSuccess("Задача создана и добавлена в проект.");}};
  const acceptanceSummary=taskAcceptance==="none"?"Приёмка не требуется":taskAcceptance==="author"?"Результат принимает автор задачи":"Результат принимает ответственный";
  const lifecycle=<div className="project-life">{project.status==="draft"&&<button disabled={!editable||busy} onClick={()=>action("start",{version:project.version})}>Начать</button>}{project.status==="active"&&<button disabled={!editable||busy} onClick={()=>action("hold",{version:project.version})}>Приостановить</button>}{project.status==="on_hold"&&<button disabled={!editable||busy} onClick={()=>action("start",{version:project.version})}>Продолжить</button>}{["active","on_hold"].includes(project.status)&&<button disabled={!editable||busy} onClick={()=>action("complete",{version:project.version})}>Завершить</button>}</div>;

  return <main className="project-page project-detail-ux">
    <button className="project-back" onClick={()=>navigate("/projects")}>← Все проекты</button>
    <header className="project-compact-head"><div><div className="project-kicker"><span>{project.number}</span><b>{statusName[project.status]||project.status}</b>{project.is_archived&&<span>Архив</span>}</div><h1>{project.name}</h1><p>Руководитель: {project.manager_name||"не назначен"} · Срок: {date(project.planned_start_at)} — {date(project.planned_end_at)}</p></div><div className="project-head-actions"><div className="project-split-add"><button className="project-primary" disabled={!editable} title={!editable?"Проект завершён, отменён или находится в архиве":""} onClick={e=>{setTaskStage("");openPanel("create",e);}}>+ Добавить задачу</button><details><summary aria-label="Другие способы добавления задачи">▾</summary><div className="project-menu"><button onClick={e=>{(e.currentTarget.closest("details") as HTMLDetailsElement)?.removeAttribute("open");openPanel("link",e);}}>Привязать существующую</button><button onClick={e=>{(e.currentTarget.closest("details") as HTMLDetailsElement)?.removeAttribute("open");openPanel("template",e);}}>Из шаблона</button></div></details></div><button disabled={!editable} onClick={e=>openPanel("settings",e)}>Настройки</button><details><summary aria-label="Дополнительные действия">•••</summary><div className="project-menu">{lifecycle}<button onClick={e=>{(e.currentTarget.closest("details") as HTMLDetailsElement)?.removeAttribute("open");openPanel("history",e);}}>История</button>{["draft","active","on_hold"].includes(project.status)&&<button onClick={()=>{const reason=window.prompt("Причина отмены проекта");if(reason?.trim())action("cancel",{version:project.version,reason});}}>Отменить проект</button>}{project.status==="completed"&&<button onClick={()=>{const reason=window.prompt("Причина повторного открытия");if(reason?.trim())action("reopen",{version:project.version,reason});}}>Открыть повторно</button>}{project.status==="cancelled"&&!project.is_archived&&<button onClick={()=>{const reason=window.prompt("Причина восстановления проекта");if(reason?.trim())action("restore",{version:project.version,reason});}}>Восстановить</button>}{["completed","cancelled"].includes(project.status)&&<button onClick={()=>{const reason=window.prompt(project.is_archived?"Причина возврата из архива":"Причина архивирования");if(reason?.trim())action(project.is_archived?"unarchive":"archive",{version:project.version,reason});}}>{project.is_archived?"Вернуть из архива":"Архивировать"}</button>}</div></details></div></header>
    {Boolean(error)&&<ErrorBanner error={error} onClose={()=>setError(undefined)}/>} {success&&<div className="project-success" role="status">{success}<button onClick={()=>setSuccess("")}>Закрыть</button></div>}
    <nav className="project-main-tabs" aria-label="Разделы проекта">{([['tasks','Задачи'],['overview','Обзор'],['team','Команда'],['files','Файлы'],['discussion','Обсуждение']] as [Tab,string][]).map(([value,label])=><button key={value} className={tab===value?"selected":""} aria-current={tab===value?"page":undefined} onClick={()=>updateUrl(value)}>{label}</button>)}</nav>
    {tab==="tasks"&&<section className="project-task-workspace"><div className="project-task-toolbar"><input aria-label="Поиск задач проекта" placeholder="Поиск по названию или номеру" value={search} onChange={e=>updateFilters(e.target.value,statusFilter,responsibleFilter)}/><select aria-label="Фильтр статуса задач" value={statusFilter} onChange={e=>updateFilters(search,e.target.value,responsibleFilter)}><option value="">Все статусы</option>{Object.entries(statusName).filter(([x])=>["draft","open","in_progress","waiting","review","completed","cancelled"].includes(x)).map(([x,y])=><option value={x} key={x}>{y}</option>)}</select><select aria-label="Фильтр ответственного" value={responsibleFilter} onChange={e=>updateFilters(search,statusFilter,e.target.value)}><option value="">Все ответственные</option>{taskPage?.responsible_options?.map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select><div className="project-view-switch">{([["list","Список"],["board","Доска"],["timeline","Сроки"]] as [Mode,string][]).map(([x,label])=><button className={mode===x?"selected":""} key={x} onClick={()=>updateUrl("tasks",x)}>{label}</button>)}</div></div><p className="project-scope-note">Показаны результаты по всем доступным вам задачам проекта. Фильтры применяются на сервере до пагинации.</p>
      {mode==="list"&&<div className="project-stage-groups"><div className="project-task-columns"><b>Задача</b><b>Статус</b><b>Ответственный</b><b>Срок</b><span/></div>{groups.map(g=><section className="project-stage" key={g.id}><header><button aria-expanded={!collapsed[g.id]} onClick={()=>setCollapsed(x=>({...x,[g.id]:!x[g.id]}))}>{collapsed[g.id]?"▸":"▾"} {g.name}</button><span>{g.tasks.length<g.count?`показано ${g.tasks.length} из ${g.count}`:`${g.count} результатов`}</span>{editable&&<button onClick={e=>{setTaskStage(g.id==="none"?"":g.id);openPanel("create",e);}}>+ Добавить задачу</button>}</header>{!collapsed[g.id]&&<div className="project-task-list">{g.tasks.map(taskCard)}{!g.tasks.length&&g.count===0&&<p>В этой группе нет задач.</p>}{!g.tasks.length&&g.count>0&&<p>Задачи этой группы находятся на другой странице результатов.</p>}</div>}</section>)}</div>}
      {mode==="board"&&<div className="project-board">{["draft","open","in_progress","waiting","review","completed","cancelled"].map(s=><div key={s} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const task=tasks.find(t=>t.id===e.dataTransfer.getData("text/plain"));if(task)boardMove(task,s);}}><h3>{statusName[s]}</h3>{visibleTasks.filter(t=>t.status===s).map(taskCard)}</div>)}</div>}
      {mode==="timeline"&&<div className="project-timeline">{[...visibleTasks.map(t=>({kind:"task",due:t.due_at,item:t})),...milestones.map(m=>({kind:"milestone",due:m.due_at,item:m}))].sort((a,b)=>(a.due||"9999").localeCompare(b.due||"9999")).map(x=>x.kind==="task"?taskCard(x.item as Task):<div className="project-row" key={(x.item as Milestone).id}><strong>Контрольная точка · {(x.item as Milestone).name}</strong><small>{date(x.due)}</small></div>)}</div>}
      {!tasks.length&&<div className="project-empty"><strong>{taskPage?.count===0?"Добавьте первую задачу. Этапы можно настроить позже.":"Доступных вам задач нет."}</strong></div>}{tasks.length>0&&!visibleTasks.length&&<div className="project-empty">По выбранным фильтрам ничего не найдено.</div>}
      {editable&&<div className="project-stage-add">{!showStageCreate?<button onClick={()=>setShowStageCreate(true)}>+ Добавить этап</button>:<><input autoFocus aria-label="Название нового этапа" value={stageName} onChange={e=>setStageName(e.target.value)} placeholder="Название этапа"/><button disabled={!stageName.trim()||busy} onClick={async()=>{if(await action("stages",{version:project.version,name:stageName.trim(),position:stages.length+1})){setStageName("");setShowStageCreate(false);}}}>Добавить этап</button><button onClick={()=>{setStageName("");setShowStageCreate(false);}}>Отмена</button></>}</div>}
      {taskPage&&<div className="project-pager"><button disabled={!taskPage.previous} onClick={()=>changePage(taskPageNo-1)}>← Назад</button><span>Страница {taskPageNo} · всего доступно {taskPage.count}</span><button disabled={!taskPage.next} onClick={()=>changePage(taskPageNo+1)}>Вперёд →</button></div>}
    </section>}
    {tab==="overview"&&<section className="project-overview"><div><h2>О проекте</h2><dl><dt>Цель</dt><dd>{project.goal||"Не указана"}</dd><dt>Описание</dt><dd>{project.description||"Не указано"}</dd><dt>Ожидаемый результат</dt><dd>{project.expected_result||"Не указан"}</dd></dl></div><div className="project-stat-line"><span><b>{counters?.progress_percent??"—"}%</b> прогресс</span><span><b>{counters?.active??"—"}</b> в работе</span><span><b>{counters?.overdue??"—"}</b> просрочено</span><span><b>{counters?.review??"—"}</b> на приёмке</span><small>По доступным вам задачам</small></div><div className="project-overview-grid"><section><h2>Ближайшие контрольные точки</h2>{milestones.slice(0,5).map(m=><div className="project-row" key={m.id}><strong>{m.name}</strong><small>{date(m.due_at)}</small></div>)}{!milestones.length&&<p>Предстоящих точек нет.</p>}</section><section><h2>Задачи по ответственным</h2>{counters?.by_responsible?.map((x:any)=><div className="project-row" key={x.employee_id||"none"}><strong>{x.employee_name}</strong><small>Активных: {x.active} · просроченных: {x.overdue}</small></div>)}{!counters?.by_responsible?.length&&<p>Доступных задач нет.</p>}</section></div></section>}
    {tab==="team"&&<section className="project-section"><div className="project-section-title"><h2>Команда проекта</h2>{editable&&<button onClick={e=>openPanel("member",e)}>Добавить участника</button>}</div>{members.map(x=><div className={`project-member ${x.role==="manager"?"manager":""}`} key={x.id}><div><strong>{x.employee_name}</strong><span>{roleName[x.role]||x.role}</span></div>{editable&&x.role!=="manager"&&<button onClick={()=>action(`members/${x.id}/remove`,{version:project.version})}>Убрать</button>}</div>)}{!members.length&&<p>Участники ещё не добавлены.</p>}</section>}
    {tab==="files"&&<section className="project-section"><div className="project-section-title"><h2>Файлы проекта</h2><label className={`project-upload ${!editable?"disabled":""}`}>Загрузить<input aria-label="Загрузить файл проекта" type="file" disabled={!editable||busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const data=new FormData();data.append("file",file);setBusy(true);try{await workRequest(`${root}${id}/attachments/`,{method:"POST",body:data});setAttachments(await get(`${id}/attachments/`));}catch(x){setError(x);}finally{setBusy(false);e.target.value="";}}}/></label></div>{attachments.map(x=><div className="project-file" key={x.id}><div><strong>{x.original_filename}</strong><small>{x.size} байт</small></div><button onClick={()=>workDownload(`${root}${id}/attachments/${x.id}/download/`,x.original_filename).catch(setError)}>Скачать</button></div>)}{!attachments.length&&<p>Файлов пока нет.</p>}</section>}
    {tab==="discussion"&&<section className="project-section"><h2>Обсуждение</h2><div className="project-comments">{comments.map(x=><article key={x.id}><strong>{x.author_name}</strong><p>{x.body}</p><small>{date(x.created_at)}</small></article>)}</div><label>Сообщение<textarea value={comment} onChange={e=>setComment(e.target.value)} rows={4}/></label><label>Упомянуть сотрудника<select value={mention} onChange={e=>setMention(e.target.value)}><option value="">Без упоминания</option>{people.map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select></label><button className="project-primary" disabled={busy||!comment.trim()} onClick={async()=>{if(await action("comments",{body:comment.trim(),mentions:mention?[mention]:[]})){setComment("");setMention("");setComments(await get(`${id}/comments/`));}}}>Отправить</button></section>}
    {panel&&<div className="project-drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closePanel();}}><aside className="project-drawer" role="dialog" aria-modal="true" aria-label={panel==="settings"?"Настройки проекта":"Действие с проектом"}><header><h2>{panel==="create"?"Новая задача":panel==="link"?"Привязать задачу":panel==="template"?"Задача из шаблона":panel==="settings"?"Настройки проекта":panel==="history"?"История проекта":panel==="member"?"Новый участник":""}</h2><button aria-label="Закрыть" onClick={()=>closePanel()}>×</button></header>
      {panel==="create"&&<div className="project-form"><label>Название задачи<input autoFocus value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/>{!taskTitle.trim()&&<small>Обязательное поле</small>}</label><label>Ответственный<select value={responsibleTarget} onChange={e=>setResponsibleTarget(e.target.value)}><option value="">Не назначен</option>{targets.map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select></label><label>Срок<input type="datetime-local" value={taskDue} onChange={e=>setTaskDue(e.target.value)}/></label><details><summary>Дополнительно</summary><label>Описание<textarea rows={3} value={taskDescription} onChange={e=>setTaskDescription(e.target.value)}/></label><label>Исполнитель<select value={executorTarget} onChange={e=>setExecutorTarget(e.target.value)}><option value="">Не назначен</option>{targets.map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select></label><label>Этап<select value={taskStage} onChange={e=>setTaskStage(e.target.value)}><option value="">Без этапа</option>{stages.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Приоритет<select value={taskPriority} onChange={e=>setTaskPriority(e.target.value)}><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="critical">Критический</option></select></label><label>Приёмка<select value={taskAcceptance} onChange={e=>setTaskAcceptance(e.target.value)}><option value="none">Без приёмки</option><option value="author">Автором задачи</option><option value="responsible">Ответственным</option></select><small>{acceptanceSummary}</small></label></details><footer><button onClick={()=>closePanel()}>Отмена</button><button className="project-primary" disabled={busy||!taskTitle.trim()} onClick={createTask}>{busy?"Создаём…":"Создать задачу"}</button></footer></div>}
      {panel==="link"&&<div className="project-form"><label>Найти задачу Work<input autoFocus value={linkSearch} onChange={e=>setLinkSearch(e.target.value)}/></label><label>Задача<select value={selectedTask} onChange={e=>setSelectedTask(e.target.value)}><option value="">Выберите задачу</option>{linkOptions.filter(x=>!x.project).map(x=><option value={x.id} key={x.id}>{x.number} · {x.title}</option>)}</select></label><label>Этап<select value={taskStage} onChange={e=>setTaskStage(e.target.value)}><option value="">Без этапа</option>{stages.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><footer><button onClick={()=>closePanel()}>Отмена</button><button className="project-primary" disabled={busy||!selectedTask} onClick={async()=>{const t=linkOptions.find(x=>x.id===selectedTask);if(!t)return;const detail=await workRequest<any>(`/tasks/${t.id}/`);if(await action("link-task",{project_version:project.version,task_version:detail.version,task:t.id,stage:taskStage||null})){setSelectedTask("");setLinkSearch("");closePanel(true);setSuccess("Задача привязана к проекту.");}}}>Привязать</button></footer></div>}
      {panel==="template"&&<div className="project-form"><label>Шаблон<select autoFocus value={template} onChange={e=>setTemplate(e.target.value)}><option value="">Выберите шаблон</option>{templates.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Этап<select value={taskStage} onChange={e=>setTaskStage(e.target.value)}><option value="">Без этапа</option>{stages.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><footer><button onClick={()=>closePanel()}>Отмена</button><button className="project-primary" disabled={busy||!template} onClick={async()=>{if(await action("create-task",{project_version:project.version,template,stage:taskStage||null},taskKey)){setTemplate("");setTaskKey(requestKey());closePanel(true);setSuccess("Задача создана из шаблона.");}}}>Создать</button></footer></div>}
      {panel==="settings"&&<div className="project-form">{([['name','Название'],['goal','Цель'],['description','Описание'],['result','Ожидаемый результат']] as const).map(([key,label])=><label key={key}>{label}{key==="description"?<textarea value={edit[key]} onChange={e=>setEdit(x=>({...x,[key]:e.target.value}))}/>:<input value={edit[key]} onChange={e=>setEdit(x=>({...x,[key]:e.target.value}))}/>}</label>)}<label>Руководитель<select value={edit.manager} onChange={e=>setEdit(x=>({...x,manager:e.target.value}))}><option value="">Не назначен</option>{people.map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select></label><label>Плановое начало<input type="datetime-local" value={edit.start} onChange={e=>setEdit(x=>({...x,start:e.target.value}))}/></label><label>Плановое завершение<input type="datetime-local" value={edit.end} onChange={e=>setEdit(x=>({...x,end:e.target.value}))}/></label><footer><button onClick={()=>closePanel(true)}>Отмена</button><button className="project-primary" disabled={busy||!edit.name.trim()} onClick={async()=>{setBusy(true);try{await workRequest(`${root}${id}/`,{method:"PATCH",body:JSON.stringify({version:project.version,name:edit.name.trim(),description:edit.description,goal:edit.goal,expected_result:edit.result,manager:edit.manager||null,customer:edit.customer||null,org_unit:edit.orgUnit||null,planned_start_at:edit.start?new Date(edit.start).toISOString():null,planned_end_at:edit.end?new Date(edit.end).toISOString():null})});await loadBase();closePanel(true);setSuccess("Настройки проекта сохранены.");}catch(e){setError(e);}finally{setBusy(false);}}}>Сохранить</button></footer></div>}
      {panel==="member"&&<div className="project-form"><label>Сотрудник<select value={member} onChange={e=>setMember(e.target.value)}><option value="">Выберите сотрудника</option>{people.filter(x=>!members.some(m=>m.employee===x.id)).map(x=><option value={x.id} key={x.id}>{x.display_name}</option>)}</select></label><label>Роль<select value={memberRole} onChange={e=>setMemberRole(e.target.value)}><option value="member">Участник</option><option value="observer">Наблюдатель</option></select></label><footer><button onClick={()=>closePanel(true)}>Отмена</button><button className="project-primary" disabled={busy||!member} onClick={async()=>{if(await action("members",{version:project.version,employee:member,role:memberRole})){setMembers(await get(`${id}/members/`));setMember("");closePanel(true);}}}>Добавить</button></footer></div>}
      {panel==="history"&&<div className="project-history">{history?.project.map((x,i)=><div key={`p${i}`}><strong>{actionName[x.action]||"Изменение проекта"}</strong><small>{date(x.created_at)}</small></div>)}{history?.links.map((x,i)=><div key={`l${i}`}><strong>{actionName[x.action]||"Изменение связи задачи"}</strong><small>{date(x.created_at)}</small></div>)}{history&&!history.project.length&&!history.links.length&&<p>История пока пуста.</p>}</div>}
    </aside></div>}
  </main>;
}
