# Generated by Django 5.1.5 on 2026-08-03 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=30, unique=True)),
                ('position', models.CharField(max_length=150)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Работает'), ('vacation', 'Отпуск'), ('sick', 'Больничный'), ('archived', 'Архив')], default='active', max_length=20)),
                ('work_schedule', models.CharField(default='5/2, 09:00–18:00', max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('is_demo', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.facility')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='facilities',
            field=models.ManyToManyField(related_name='employees', through='employees.EmployeeFacility', to='organizations.facility'),
        ),
        migrations.AddConstraint(
            model_name='employeefacility',
            constraint=models.UniqueConstraint(fields=('employee', 'facility'), name='unique_employee_facility'),
        ),
    ]
