# Generated by Django 5.1.5 on 2026-08-15 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_assignmenttarget_functionalgroup_and_more'),
        ('organizations', '0002_legalentity_location_orgunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.legalentity'),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='primary_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_employees', to='organizations.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Работает'), ('vacation', 'Отпуск'), ('sick', 'Больничный'), ('archived', 'Архив'), ('on_leave', 'В отпуске'), ('suspended', 'Отстранён'), ('dismissed', 'Уволен')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_targets', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_targets', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='functionalgroup',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='functional_groups', to='organizations.legalentity'),
        ),
        migrations.AddField(
            model_name='functionalgroup',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='functional_groups', to='organizations.location'),
        ),
        migrations.AddField(
            model_name='functionalgroup',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='functional_groups', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_targets', to='employees.functionalgroup'),
        ),
        migrations.AddField(
            model_name='functionalgroupmembership',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='functional_group_memberships', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='functionalgroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='employees.functionalgroup'),
        ),
        migrations.AddField(
            model_name='position',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organizations.legalentity'),
        ),
        migrations.AddField(
            model_name='position',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_targets', to='employees.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position_ref'], name='employees_e_positio_f0d623_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['org_unit'], name='employees_e_org_uni_9070c1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['legal_entity'], name='employees_e_legal_e_2a9219_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager'], name='employees_e_manager_278e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='functionalgroupmembership',
            index=models.Index(fields=['employee'], name='employees_f_employe_da3ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='functionalgroupmembership',
            index=models.Index(fields=['group'], name='employees_f_group_i_cda7c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='functionalgroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group', 'employee'), name='unique_active_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='assignmenttarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'employee')), models.Q(('employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', False), ('target_type', 'position')), models.Q(('employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', False), ('position__isnull', True), ('target_type', 'org_unit')), models.Q(('employee__isnull', True), ('functional_group__isnull', False), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'functional_group')), _connector='OR'), name='assignment_target_exactly_one_reference'),
        ),
    ]
