# Generated by Django 5.1.5 on 2026-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_legal_entity_employee_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
