# Generated by Django 5.2.17 on 2026-09-01 16:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def bootstrap_people_foundation(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    Sequence = apps.get_model("employees", "EmployeeNumberSequence")
    Assignment = apps.get_model("employees", "EmployeeAssignment")
    ManagerAssignment = apps.get_model("employees", "EmployeeManagerAssignment")

    used = set()
    for value in Employee.objects.exclude(employee_number__isnull=True).exclude(employee_number="").values_list("employee_number", flat=True):
        if value.startswith("EMP-") and value[4:].isdigit():
            used.add(int(value[4:]))
    next_value = max(used, default=0) + 1
    for employee in Employee.objects.order_by("created_at", "pk").iterator():
        if not employee.employee_number:
            while next_value in used:
                next_value += 1
            employee.employee_number = f"EMP-{next_value:06d}"
            employee.save(update_fields=["employee_number"])
            used.add(next_value)
            next_value += 1
        if any((employee.position_ref_id, employee.org_unit_id, employee.legal_entity_id, employee.primary_location_id)):
            Assignment.objects.get_or_create(
                employee_id=employee.pk,
                is_primary=True,
                status="active",
                defaults={
                    "position_id": employee.position_ref_id,
                    "org_unit_id": employee.org_unit_id,
                    "legal_entity_id": employee.legal_entity_id,
                    "location_id": employee.primary_location_id,
                    "valid_from": employee.created_at,
                },
            )
        if employee.manager_id:
            ManagerAssignment.objects.get_or_create(
                employee_id=employee.pk,
                status="active",
                defaults={"manager_id": employee.manager_id, "valid_from": employee.created_at},
            )
    Sequence.objects.update_or_create(key="employee", defaults={"next_value": max(used, default=0) + 1})


def reverse_noop(apps, schema_editor):
    # Compatibility data is intentionally retained; schema rollback removes the new tables.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeinvitation_registrationrequest'),
        ('organizations', '0002_legalentity_location_orgunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='employee', max_length=32, unique=True)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='employees/avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Работает'), ('vacation', 'Отпуск'), ('sick', 'Больничный'), ('archived', 'Архив'), ('on_leave', 'В отпуске'), ('suspended', 'Отстранён'), ('dismissed', 'Уволен'), ('inactive', 'Неактивен'), ('onboarding', 'Оформление'), ('terminated', 'Уволен')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('ended', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizational_assignments', to='employees.employee')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organizations.orgunit')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='employees.position')),
            ],
            options={
                'ordering': ['-valid_from', 'created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_e_employe_a6f533_idx'), models.Index(fields=['org_unit', 'status'], name='employees_e_org_uni_afae3e_idx'), models.Index(fields=['legal_entity', 'status'], name='employees_e_legal_e_19c516_idx'), models.Index(fields=['location', 'status'], name='employees_e_locatio_f82649_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'active')), fields=('employee',), name='one_active_primary_employee_assignment'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='employee_assignment_valid_period')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeManagerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('ended', 'Завершено')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_assignments', to='employees.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['-valid_from', 'created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_e_employe_4f9257_idx'), models.Index(fields=['manager', 'status'], name='employees_e_manager_758d6b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('employee',), name='one_active_manager_assignment'), models.CheckConstraint(condition=models.Q(('employee', models.F('manager')), _negated=True), name='employee_manager_not_self'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='employee_manager_valid_period')],
            },
        ),
        migrations.RunPython(bootstrap_people_foundation, reverse_noop),
    ]
