# Generated by Django 5.2.17 on 2026-09-01 20:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def initialize_team_sequence(apps, schema_editor):
    apps.get_model("employees", "TeamNumberSequence").objects.get_or_create(key="team", defaults={"next_value": 1})


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeenumbersequence_employee_avatar_and_more'),
        ('organizations', '0002_legalentity_location_orgunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('team_type', models.CharField(choices=[('functional', 'Функциональная'), ('cross_functional', 'Кросс-функциональная'), ('project', 'Проектная'), ('service', 'Сервисная'), ('committee', 'Комитет'), ('temporary', 'Временная'), ('other', 'Другая')], db_index=True, default='functional', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('suspended', 'Приостановлена'), ('closed', 'Закрыта')], db_index=True, default='draft', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_assignable', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Руководитель'), ('deputy', 'Заместитель'), ('member', 'Участник'), ('coordinator', 'Координатор'), ('observer', 'Наблюдатель')], default='member', max_length=24)),
                ('membership_type', models.CharField(choices=[('permanent', 'Постоянное'), ('temporary', 'Временное'), ('observer', 'Наблюдатель')], default='permanent', max_length=24)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('allocation_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_primary_in_team', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_reason', models.CharField(blank=True, max_length=240)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-valid_from', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='team', max_length=32, unique=True)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.RunPython(initialize_team_sequence, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='assignmenttarget',
            name='assignment_target_exactly_one_reference',
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='explicit_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='explicit_assignment_targets', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='strategy',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='team_role',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='assignmenttarget',
            name='target_type',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('position', 'Должность'), ('org_unit', 'Подразделение'), ('functional_group', 'Функциональная группа'), ('team', 'Команда')], max_length=32),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='lead_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='team',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.legalentity'),
        ),
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.location'),
        ),
        migrations.AddField(
            model_name='team',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='team',
            name='parent_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_teams', to='employees.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenttarget',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_targets', to='employees.team'),
        ),
        migrations.AddConstraint(
            model_name='assignmenttarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'employee'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', False), ('target_type', 'position'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', False), ('position__isnull', True), ('target_type', 'org_unit'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('functional_group__isnull', False), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'functional_group'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'team'), ('team__isnull', False)), _connector='OR'), name='assignment_target_exactly_one_reference'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships_ended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='employees.team'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['parent_team'], name='employees_t_parent__7edb39_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['legal_entity', 'status'], name='employees_t_legal_e_8ec761_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['org_unit', 'status'], name='employees_t_org_uni_b8ce9b_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['location', 'status'], name='employees_t_locatio_9df95c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['owner_employee'], name='employees_t_owner_e_79ed37_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['lead_employee'], name='employees_t_lead_em_6d0dd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_team_id')), _negated=True), name='team_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='team_valid_period'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'employee'], name='employees_t_team_id_b697a8_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'valid_from', 'valid_to'], name='employees_t_team_id_c51ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['employee', 'valid_from', 'valid_to'], name='employees_t_employe_2c8cc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='team_membership_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_percent__isnull', True), models.Q(('allocation_percent__gte', 1), ('allocation_percent__lte', 100)), _connector='OR'), name='team_membership_allocation_range'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('team', 'employee'), name='one_open_team_membership'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_in_team', True), ('role', 'lead'), ('valid_to__isnull', True)), fields=('team',), name='one_primary_team_lead'),
        ),
    ]
