# Generated by Django 5.2.17 on 2026-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_team_teammembership_teamnumbersequence_and_more'),
        ('organizations', '0003_orgunit_description_orgunit_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmenttarget',
            name='assignment_target_exactly_one_reference',
        ),
        migrations.AddConstraint(
            model_name='assignmenttarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('explicit_employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'employee'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('explicit_employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', False), ('target_type', 'position'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('explicit_employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', False), ('position__isnull', True), ('target_type', 'org_unit'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('explicit_employee__isnull', True), ('functional_group__isnull', False), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'functional_group'), ('team__isnull', True)), models.Q(('employee__isnull', True), ('functional_group__isnull', True), ('org_unit__isnull', True), ('position__isnull', True), ('target_type', 'team'), ('team__isnull', False)), _connector='OR'), name='assignment_target_exactly_one_reference'),
        ),
    ]
