# Generated by Django 5.1.5 on 2026-09-02 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_team_membership_no_period_overlap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('additional_email', models.EmailField(blank=True, max_length=254)),
                ('additional_phone', models.CharField(blank=True, max_length=40)),
                ('timezone', models.CharField(default='Asia/Novosibirsk', max_length=64)),
                ('preferred_language', models.CharField(default='ru', max_length=12)),
                ('bio_visibility', models.CharField(choices=[('private', 'Только я и HR'), ('managers', 'Руководители'), ('team', 'Команды'), ('organization', 'Организация')], default='organization', max_length=20)),
                ('additional_email_visibility', models.CharField(choices=[('private', 'Только я и HR'), ('managers', 'Руководители'), ('team', 'Команды'), ('organization', 'Организация')], default='private', max_length=20)),
                ('additional_phone_visibility', models.CharField(choices=[('private', 'Только я и HR'), ('managers', 'Руководители'), ('team', 'Команды'), ('organization', 'Организация')], default='private', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDataChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('legal_name', 'ФИО'), ('work_email', 'Рабочая почта'), ('work_phone', 'Рабочий телефон')], max_length=24)),
                ('requested_value', models.JSONField(default=dict)),
                ('current_value_snapshot', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('submitted', 'Отправлен'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён'), ('applied', 'Применён'), ('failed', 'Ошибка')], db_index=True, default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, max_length=500)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_change_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_change_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'status', 'submitted_at'], name='employees_e_employe_fd9dea_idx')],
            },
        ),
    ]
