# Generated by Django 5.2.17 on 2026-09-02 21:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_invitation_lifecycle(apps, schema_editor):
    Invitation = apps.get_model('employees', 'EmployeeInvitation')
    Invitation.objects.filter(used_at__isnull=False).update(status='accepted')
    Invitation.objects.filter(used_at__isnull=True, revoked_at__isnull=False).update(status='revoked')


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_seed_profile_permissions'),
        ('organizations', '0003_orgunit_description_orgunit_metadata_and_more'),
        ('work_tasks', '0003_alter_task_source_type_taskrecurrencerule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLoginProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_completed', models.BooleanField(default=False)),
                ('timezone_completed', models.BooleanField(default=False)),
                ('visibility_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активен'), ('paused', 'Приостановлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStepInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_snapshot', models.CharField(max_length=240)),
                ('description_snapshot', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('blocked', 'Заблокирован'), ('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('skipped', 'Пропущен'), ('cancelled', 'Отменён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20)),
                ('resolution_detail', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], db_index=True, default='draft', max_length=16)),
                ('scope', models.CharField(choices=[('global', 'Глобально'), ('legal_entity', 'Юридическое лицо'), ('org_unit', 'Подразделение'), ('location', 'Локация'), ('position', 'Должность'), ('team', 'Команда')], db_index=True, default='global', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingTemplateStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('profile', 'Профиль'), ('acknowledgement', 'Ознакомление'), ('manual', 'Ручной шаг'), ('task', 'Задача'), ('link', 'Ссылка'), ('learning_placeholder', 'Обучение')], max_length=32)),
                ('position', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('due_offset', models.DurationField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True)),
                ('responsible_strategy', models.CharField(choices=[('self', 'Сам сотрудник'), ('direct_manager', 'Прямой руководитель'), ('position', 'Должность'), ('org_unit', 'Подразделение'), ('team_lead', 'Руководитель команды'), ('team_role', 'Роль команды'), ('explicit_employee', 'Сотрудник'), ('assignment_target', 'Цель назначения')], default='self', max_length=32)),
                ('team_role', models.CharField(blank=True, max_length=24)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(max_length=200)),
                ('description_snapshot', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['template_id', 'number'],
            },
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_invitations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='revoke_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('sent', 'Отправлено'), ('accepted', 'Принято'), ('revoked', 'Отозвано'), ('expired', 'Истекло')], db_index=True, default='created', max_length=16),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='token_prefix',
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='employeeinvitation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_invitation_lifecycle, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='employeeinvitation',
            index=models.Index(fields=['status', 'expires_at'], name='employees_e_status_c69a31_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at')), ('status', 'expired'), _connector='OR'), name='employee_invitation_expiry_after_creation'),
        ),
        migrations.AddField(
            model_name='firstloginprogress',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_login_progress', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='onboardinginstance',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_instances_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardinginstance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_instances', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='onboardingstepinstance',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_onboarding_steps', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='onboardingstepinstance',
            name='onboarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='employees.onboardinginstance'),
        ),
        migrations.AddField(
            model_name='onboardingstepinstance',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_onboarding_steps', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='onboardingstepinstance',
            name='skipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skipped_onboarding_steps', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='onboardingstepinstance',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_step', to='work_tasks.task'),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_templates', to='organizations.legalentity'),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_templates', to='organizations.location'),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_templates', to='organizations.orgunit'),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_templates', to='employees.position'),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_templates', to='employees.team'),
        ),
        migrations.AddField(
            model_name='onboardingtemplatestep',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='employees.onboardingtemplatestep'),
        ),
        migrations.AddField(
            model_name='onboardingtemplatestep',
            name='explicit_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='explicit_onboarding_steps', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='onboardingtemplatestep',
            name='responsible_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_steps', to='employees.assignmenttarget'),
        ),
        migrations.AddField(
            model_name='onboardingtemplatestep',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_steps', to='work_tasks.tasktemplate'),
        ),
        migrations.AddField(
            model_name='onboardingstepinstance',
            name='template_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='employees.onboardingtemplatestep'),
        ),
        migrations.AddField(
            model_name='onboardingtemplateversion',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_versions_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingtemplateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='employees.onboardingtemplate'),
        ),
        migrations.AddField(
            model_name='onboardingtemplatestep',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='employees.onboardingtemplateversion'),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for_templates', to='employees.onboardingtemplateversion'),
        ),
        migrations.AddField(
            model_name='onboardinginstance',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='employees.onboardingtemplateversion'),
        ),
        migrations.AddIndex(
            model_name='onboardingstepinstance',
            index=models.Index(fields=['onboarding', 'status'], name='employees_o_onboard_c4661e_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingstepinstance',
            index=models.Index(fields=['status', 'due_at'], name='employees_o_status_4ac50d_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingstepinstance',
            constraint=models.UniqueConstraint(fields=('onboarding', 'template_step'), name='unique_onboarding_step_instance'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='unique_onboarding_template_version'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplatestep',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='unique_onboarding_step_key'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplatestep',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='unique_onboarding_step_position'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['status', 'scope'], name='employees_o_status_447d23_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['legal_entity', 'org_unit', 'position'], name='employees_o_legal_e_c080d2_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardinginstance',
            index=models.Index(fields=['employee', 'status'], name='employees_o_employe_326e42_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardinginstance',
            index=models.Index(fields=['status', 'created_at'], name='employees_o_status_e4b0e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardinginstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active', 'paused'])), fields=('employee',), name='one_active_onboarding_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='onboardinginstance',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__lte', 100)), name='onboarding_progress_lte_100'),
        ),
    ]
