# Generated by Django 5.2.17 on 2026-09-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_seed_onboarding_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_access_state',
            field=models.CharField(choices=[('normal', 'Обычный доступ'), ('suspended', 'Доступ приостановлен'), ('blocked', 'Доступ заблокирован'), ('reactivation_required', 'Требуется реактивация')], db_index=True, default='normal', max_length=24),
        ),
    ]
