# Generated by Django 5.1.5 on 2026-08-15 09:20

import django.db.models.deletion
import uuid


def create_task_sequence(apps, schema_editor):
    apps.get_model('work_tasks', 'TaskNumberSequence').objects.get_or_create(key='task', defaults={'value': 0})
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('organizations', '0002_legalentity_location_orgunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNumberSequence',
            fields=[
                ('key', models.CharField(default='task', max_length=32, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыта'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('review', 'На приёмке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, default='normal', max_length=20)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('initial_due_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_reason', models.CharField(blank=True, choices=[('waiting_requester', 'Ожидание инициатора'), ('waiting_external', 'Внешняя зависимость'), ('waiting_material', 'Ожидание материалов'), ('waiting_approval', 'Ожидание согласования'), ('waiting_other', 'Другое')], max_length=32)),
                ('waiting_comment', models.TextField(blank=True)),
                ('expected_resume_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('completion_comment', models.TextField(blank=True)),
                ('completion_policy', models.CharField(choices=[('manual', 'Ручное завершение'), ('all_children_completed', 'Все подзадачи завершены')], default='manual', max_length=32)),
                ('acceptance_policy', models.CharField(choices=[('none', 'Без приёмки'), ('author', 'Автор'), ('responsible', 'Ответственный')], default='none', max_length=24)),
                ('source_type', models.CharField(choices=[('manual', 'Вручную'), ('request', 'Заявка'), ('project', 'Проект'), ('incident', 'Инцидент'), ('checklist', 'Чек-лист'), ('automation', 'Автоматизация'), ('api', 'API')], default='manual', max_length=24)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_work_tasks', to='employees.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_tasks', to=settings.AUTH_USER_MODEL)),
                ('executor_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_work_tasks', to='employees.employee')),
                ('executor_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_work_tasks', to='employees.assignmenttarget')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks', to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks', to='organizations.orgunit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='work_tasks.task')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_work_tasks', to='employees.employee')),
                ('responsible_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_work_tasks', to='employees.assignmenttarget')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_work_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('responsible', 'Ответственный'), ('executor', 'Исполнитель')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignment_changes', to='employees.employee')),
                ('new_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_task_assignments', to='employees.employee')),
                ('new_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_task_assignments', to='employees.assignmenttarget')),
                ('old_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_task_assignments', to='employees.employee')),
                ('old_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_task_assignments', to='employees.assignmenttarget')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='work_tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDeadlineHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_due_at', models.DateTimeField(blank=True, null=True)),
                ('new_due_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_deadline_changes', to='employees.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_history', to='work_tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReviewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Отправлено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_reviews', to='employees.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_history', to='work_tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Черновик'), ('open', 'Открыта'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('review', 'На приёмке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыта'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('review', 'На приёмке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_status_changes', to='employees.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='work_tasks.task')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskWaitingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('waiting_requester', 'Ожидание инициатора'), ('waiting_external', 'Внешняя зависимость'), ('waiting_material', 'Ожидание материалов'), ('waiting_approval', 'Ожидание согласования'), ('waiting_other', 'Другое')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expected_resume_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_waiting_periods', to='employees.employee')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_waiting_periods', to='employees.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiting_periods', to='work_tasks.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['author'], name='work_tasks__author__99bf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible_employee'], name='work_tasks__respons_2cb3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['executor_employee'], name='work_tasks__executo_fd8957_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['org_unit'], name='work_tasks__org_uni_a8b230_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['legal_entity'], name='work_tasks__legal_e_003115_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['location'], name='work_tasks__locatio_e57f69_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent'], name='work_tasks__parent__b4551d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_at'], name='work_tasks__status_5ba110_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('planned_start_at__isnull', True), ('due_at__isnull', True), ('planned_start_at__lte', models.F('due_at')), _connector='OR'), name='work_task_planned_before_due'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='work_task_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='work_task_completed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='work_task_cancelled_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='taskwaitingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('task',), name='one_active_waiting_period_per_task'),
        ),
        migrations.RunPython(create_task_sequence, migrations.RunPython.noop),
    ]
