# Generated by Django 5.1.5 on 2026-08-15 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('organizations', '0002_legalentity_location_orgunit'),
        ('work_tasks', '0002_checklisttemplate_taskchecklist_taskcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Вручную'), ('request', 'Заявка'), ('project', 'Проект'), ('incident', 'Инцидент'), ('checklist', 'Чек-лист'), ('automation', 'Автоматизация'), ('api', 'API'), ('template', 'Шаблон'), ('recurrence', 'Повторение')], default='manual', max_length=24),
        ),
        migrations.CreateModel(
            name='TaskRecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rrule', models.CharField(max_length=500)),
                ('timezone', models.CharField(max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('next_occurrence_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_recurrences', to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_tasks', to='work_tasks.taskrecurrencerule'),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_title', models.CharField(max_length=240)),
                ('task_description', models.TextField(blank=True)),
                ('default_priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20)),
                ('acceptance_policy', models.CharField(choices=[('none', 'Без приёмки'), ('author', 'Автор'), ('responsible', 'Ответственный')], default='none', max_length=24)),
                ('completion_policy', models.CharField(choices=[('manual', 'Ручное завершение'), ('all_children_completed', 'Все подзадачи завершены')], default='manual', max_length=32)),
                ('planned_start_offset', models.DurationField(blank=True, null=True)),
                ('deadline_rule', models.CharField(choices=[('none', 'Без срока'), ('after_creation', 'После создания'), ('after_planned_start', 'После планового начала')], default='none', max_length=32)),
                ('deadline_offset', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_templates', to='employees.employee')),
                ('executor_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_task_templates', to='employees.assignmenttarget')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', to='organizations.orgunit')),
                ('responsible_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_task_templates', to='employees.assignmenttarget')),
            ],
        ),
        migrations.AddField(
            model_name='taskrecurrencerule',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrence_rules', to='work_tasks.tasktemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='work_tasks.tasktemplate'),
        ),
        migrations.CreateModel(
            name='TaskTemplateChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_template_links', to='work_tasks.checklisttemplate')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_links', to='work_tasks.tasktemplate')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='checklist_templates',
            field=models.ManyToManyField(related_name='task_templates', through='work_tasks.TaskTemplateChecklist', to='work_tasks.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('generated', 'Создано'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True)),
                ('skipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skipped_task_occurrences', to='employees.employee')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_occurrence', to='work_tasks.task')),
                ('recurrence_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='work_tasks.taskrecurrencerule')),
            ],
            options={
                'ordering': ('-occurrence_at', '-id'),
                'indexes': [models.Index(fields=['status', 'occurrence_at'], name='work_tasks__status_177f03_idx')],
                'constraints': [models.UniqueConstraint(fields=('recurrence_rule', 'occurrence_at'), name='unique_task_recurrence_occurrence')],
            },
        ),
        migrations.CreateModel(
            name='TaskSavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('filters', models.JSONField(default=dict)),
                ('ordering', models.CharField(default='-created_at', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_saved_views', to='employees.employee')),
            ],
            options={
                'ordering': ('name', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner', 'name'), name='unique_active_saved_view_name'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('owner',), name='one_default_task_saved_view')],
            },
        ),
        migrations.AddIndex(
            model_name='taskrecurrencerule',
            index=models.Index(fields=['is_active', 'next_occurrence_at'], name='work_tasks__is_acti_4cccbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplatechecklist',
            constraint=models.UniqueConstraint(fields=('task_template', 'checklist_template'), name='unique_task_template_checklist'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplatechecklist',
            constraint=models.UniqueConstraint(fields=('task_template', 'position'), name='unique_task_template_checklist_position'),
        ),
    ]
