# Generated by Django 5.1.5 on 2026-08-27 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('organizations', '0002_legalentity_location_orgunit'),
        ('service_requests', '0004_servicerequestcomment_servicerequestcommentmention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('timezone', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_business_calendars', to='employees.employee')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BusinessCalendarException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('non_working_day', 'Non-working day'), ('working_day', 'Working day'), ('custom_hours', 'Custom hours')], max_length=24)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='sla.businesscalendar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_calendar_exceptions', to='employees.employee')),
            ],
            options={
                'ordering': ('date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BusinessCalendarExceptionInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='sla.businesscalendarexception')),
            ],
            options={
                'ordering': ('position', 'start_time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BusinessCalendarVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('schedule_snapshot', models.JSONField()),
                ('exceptions_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sla.businesscalendar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_calendar_versions', to='employees.employee')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='businesscalendar',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_calendar', to='sla.businesscalendarversion'),
        ),
        migrations.CreateModel(
            name='BusinessCalendarWorkingInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_intervals', to='sla.businesscalendar')),
            ],
            options={
                'ordering': ('weekday', 'position', 'start_time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('draft_time_mode', models.CharField(choices=[('business_time', 'Business time'), ('elapsed_time', 'Elapsed time')], default='elapsed_time', max_length=20)),
                ('draft_response_duration_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('draft_resolution_duration_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('draft_pause_policy', models.CharField(choices=[('none', 'None'), ('waiting_requester', 'Waiting requester'), ('waiting_external', 'Waiting external'), ('waiting_requester_and_external', 'Requester and external')], default='none', max_length=40)),
                ('draft_thresholds', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sla_policies', to='employees.employee')),
                ('draft_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_sla_policies', to='sla.businesscalendar')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SLAPolicyAssignmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('request_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_assignment_rules', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_assignment_rules', to='organizations.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_assignment_rules', to='organizations.orgunit')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='sla.slapolicy')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_assignment_rules', to='service_requests.requesttype')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_assignment_rules', to='service_requests.service')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SLAPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('time_mode', models.CharField(choices=[('business_time', 'Business time'), ('elapsed_time', 'Elapsed time')], max_length=20)),
                ('response_duration_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolution_duration_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pause_policy', models.CharField(choices=[('none', 'None'), ('waiting_requester', 'Waiting requester'), ('waiting_external', 'Waiting external'), ('waiting_requester_and_external', 'Requester and external')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_calendar_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policy_versions', to='sla.businesscalendarversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_sla_policy_versions', to='employees.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sla.slapolicy')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_policy', to='sla.slapolicyversion'),
        ),
        migrations.CreateModel(
            name='SLAWarningThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('response', 'Response'), ('resolution', 'Resolution')], max_length=16)),
                ('threshold_percent', models.PositiveSmallIntegerField()),
                ('code', models.CharField(blank=True, max_length=64)),
                ('position', models.PositiveIntegerField(default=0)),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warning_thresholds', to='sla.slapolicyversion')),
            ],
            options={
                'ordering': ('metric_type', 'position', 'threshold_percent'),
            },
        ),
        migrations.AddIndex(
            model_name='businesscalendarexception',
            index=models.Index(fields=['calendar', 'date'], name='sla_busines_calenda_b3c6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesscalendarexception',
            constraint=models.UniqueConstraint(fields=('calendar', 'date'), name='unique_calendar_exception_date'),
        ),
        migrations.AddConstraint(
            model_name='businesscalendarversion',
            constraint=models.UniqueConstraint(fields=('calendar', 'version'), name='unique_business_calendar_version'),
        ),
        migrations.AddConstraint(
            model_name='businesscalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_business_calendar'),
        ),
        migrations.AddIndex(
            model_name='businesscalendarworkinginterval',
            index=models.Index(fields=['calendar', 'weekday', 'is_active'], name='sla_busines_calenda_ee10f1_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicyassignmentrule',
            index=models.Index(fields=['request_type'], name='sla_slapoli_request_d8f5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicyassignmentrule',
            index=models.Index(fields=['service'], name='sla_slapoli_service_042fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicyassignmentrule',
            index=models.Index(fields=['request_priority'], name='sla_slapoli_request_0f3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicyassignmentrule',
            index=models.Index(fields=['legal_entity'], name='sla_slapoli_legal_e_2bc3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicyassignmentrule',
            index=models.Index(fields=['org_unit'], name='sla_slapoli_org_uni_a8460c_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicyassignmentrule',
            index=models.Index(fields=['location'], name='sla_slapoli_locatio_57770e_idx'),
        ),
        migrations.AddConstraint(
            model_name='slapolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version'), name='unique_sla_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='slapolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('business_calendar_version__isnull', True), ('time_mode', 'elapsed_time')), models.Q(('business_calendar_version__isnull', False), ('time_mode', 'business_time')), _connector='OR'), name='sla_policy_version_calendar_mode'),
        ),
        migrations.AddConstraint(
            model_name='slapolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_from__lt', models.F('effective_to')), _connector='OR'), name='sla_policy_effective_interval'),
        ),
        migrations.AddConstraint(
            model_name='slawarningthreshold',
            constraint=models.UniqueConstraint(fields=('policy_version', 'metric_type', 'threshold_percent'), name='unique_sla_warning_threshold'),
        ),
        migrations.AddConstraint(
            model_name='slawarningthreshold',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_percent__gt', 0), ('threshold_percent__lte', 100)), name='sla_warning_threshold_range'),
        ),
    ]
