# Generated by Django 5.1.5 on 2026-08-28 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0004_servicerequestcomment_servicerequestcommentmention_and_more'),
        ('sla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('calendar_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_instances', to='sla.businesscalendarversion')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_instances', to='sla.slapolicyversion')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sla_instance', to='service_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='SLAResolutionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sla_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_cycles', to='sla.slainstance')),
            ],
            options={
                'ordering': ('cycle_number',),
            },
        ),
        migrations.CreateModel(
            name='SLAPausePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('waiting_requester', 'Waiting requester'), ('waiting_external', 'Waiting external')], max_length=24)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('business_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sla_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pause_periods', to='sla.slainstance')),
                ('resolution_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pause_periods', to='sla.slaresolutioncycle')),
            ],
            options={
                'ordering': ('started_at',),
            },
        ),
        migrations.CreateModel(
            name='SLAMetricInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('response', 'Response'), ('resolution', 'Resolution')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('achieved', 'Achieved'), ('breached', 'Breached'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('duration_seconds', models.PositiveBigIntegerField()),
                ('started_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('sla_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='sla.slainstance')),
                ('resolution_cycle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metric', to='sla.slaresolutioncycle')),
            ],
        ),
        migrations.CreateModel(
            name='SLAThresholdEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threshold_percent', models.PositiveSmallIntegerField()),
                ('reached_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threshold_events', to='sla.slametricinstance')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_events', to='sla.slawarningthreshold')),
            ],
            options={
                'ordering': ('reached_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='slainstance',
            index=models.Index(fields=['status', 'updated_at'], name='sla_slainst_status_b3d50d_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaresolutioncycle',
            constraint=models.UniqueConstraint(fields=('sla_instance', 'cycle_number'), name='unique_sla_resolution_cycle'),
        ),
        migrations.AddIndex(
            model_name='slapauseperiod',
            index=models.Index(fields=['sla_instance', 'ended_at'], name='sla_slapaus_sla_ins_598ff2_idx'),
        ),
        migrations.AddConstraint(
            model_name='slapauseperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('sla_instance',), name='unique_active_sla_pause'),
        ),
        migrations.AddIndex(
            model_name='slametricinstance',
            index=models.Index(fields=['status', 'due_at'], name='sla_slametr_status_241fa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='slametricinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('metric_type', 'response')), fields=('sla_instance',), name='unique_response_metric_per_sla'),
        ),
        migrations.AddConstraint(
            model_name='slametricinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('metric_type', 'response'), ('resolution_cycle__isnull', True)), models.Q(('metric_type', 'resolution'), ('resolution_cycle__isnull', False)), _connector='OR'), name='sla_metric_cycle_kind'),
        ),
        migrations.AddConstraint(
            model_name='slathresholdevent',
            constraint=models.UniqueConstraint(fields=('metric_instance', 'threshold'), name='unique_sla_metric_threshold_event'),
        ),
    ]
