# Generated by Django 5.1.5 on 2026-08-28 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_position_created_at_alter_position_updated_at'),
        ('sla', '0002_slainstance_slaresolutioncycle_slapauseperiod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_escalation_policies', to='employees.employee')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EscalationPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('rules_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_escalation_policy_versions', to='employees.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sla.escalationpolicy')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_policy', to='sla.escalationpolicyversion'),
        ),
        migrations.CreateModel(
            name='EscalationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('sla_instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_instance', to='sla.slainstance')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_instances', to='sla.escalationpolicyversion')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('on_warning', 'On warning'), ('on_breach', 'On breach'), ('after_breach_duration', 'After breach duration')], max_length=32)),
                ('metric_type', models.CharField(choices=[('response', 'Response'), ('resolution', 'Resolution')], max_length=16)),
                ('threshold_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delay_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_rules', to='sla.escalationpolicy')),
            ],
            options={
                'ordering': ('level', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EscalationActionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('request_notification', 'Request notification'), ('add_watcher', 'Add watcher'), ('change_priority', 'Change priority'), ('reassign', 'Reassign')], max_length=32)),
                ('target_type', models.CharField(blank=True, choices=[('request_executor', 'Request executor'), ('request_responsible', 'Request responsible'), ('request_requester', 'Request requester'), ('request_executor_manager', 'Executor manager'), ('request_responsible_manager', 'Responsible manager'), ('assignment_target', 'Assignment target')], max_length=40)),
                ('target_config', models.JSONField(blank=True, default=dict)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('assignment_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_actions', to='employees.assignmenttarget')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sla.escalationrule')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EscalationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_key', models.UUIDField()),
                ('rule_snapshot', models.JSONField()),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalation_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='sla.escalationinstance')),
                ('metric_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_schedules', to='sla.slametricinstance')),
            ],
        ),
        migrations.CreateModel(
            name='SLAEscalationBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_escalation_bindings', to='employees.employee')),
                ('escalation_policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_bindings', to='sla.escalationpolicyversion')),
                ('sla_policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_bindings', to='sla.slapolicyversion')),
            ],
            options={
                'ordering': ('-effective_from', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EscalationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_key', models.UUIDField()),
                ('action_key', models.UUIDField()),
                ('rule_snapshot', models.JSONField()),
                ('action_snapshot', models.JSONField()),
                ('trigger_type', models.CharField(choices=[('on_warning', 'On warning'), ('on_breach', 'On breach'), ('after_breach_duration', 'After breach duration')], max_length=32)),
                ('triggered_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('request_notification', 'Request notification'), ('add_watcher', 'Add watcher'), ('change_priority', 'Change priority'), ('reassign', 'Reassign')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('target_snapshot', models.JSONField(blank=True, default=list)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_executions', to='sla.slametricinstance')),
                ('resolution_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_executions', to='sla.slaresolutioncycle')),
                ('escalation_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='sla.escalationinstance')),
            ],
            options={
                'ordering': ('triggered_at', 'created_at'),
                'indexes': [models.Index(fields=['status', 'triggered_at'], name='sla_escalat_status_b97bd0_idx')],
                'constraints': [models.UniqueConstraint(fields=('escalation_instance', 'metric_instance', 'rule_key', 'action_key'), name='unique_escalation_execution_context')],
            },
        ),
        migrations.AddConstraint(
            model_name='escalationpolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version'), name='unique_escalation_policy_version'),
        ),
        migrations.AddIndex(
            model_name='escalationinstance',
            index=models.Index(fields=['status', 'updated_at'], name='sla_escalat_status_8f02b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='escalationrule',
            constraint=models.CheckConstraint(condition=models.Q(('level__gt', 0)), name='escalation_rule_positive_level'),
        ),
        migrations.AddIndex(
            model_name='escalationschedule',
            index=models.Index(fields=['status', 'due_at'], name='sla_escalat_status_04378a_idx'),
        ),
        migrations.AddConstraint(
            model_name='escalationschedule',
            constraint=models.UniqueConstraint(fields=('escalation_instance', 'metric_instance', 'rule_key'), name='unique_escalation_schedule_context'),
        ),
        migrations.AddIndex(
            model_name='slaescalationbinding',
            index=models.Index(fields=['sla_policy_version', 'is_active'], name='sla_slaesca_sla_pol_b2b4c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaescalationbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sla_policy_version',), name='unique_active_sla_escalation_binding'),
        ),
    ]
