FROM ays-connect-frontend-phase16a:latest AS frontend_deps
FROM mcr.microsoft.com/playwright:v1.62.1-noble
COPY --from=frontend_deps /app/node_modules /app/node_modules
COPY --from=frontend_deps /app/package.json /app/package.json
WORKDIR /app
